const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='156bc7b7aca9b3009ad6779ccf6bd8196b42461e')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v128: files in and out on a phone. Saving (the adviser pack, all cases, a calendar reminder) goes through the
// share sheet on a phone and otherwise downloads, keeping the link for a minute and saying what actually happened;
// a picked file with no type is judged by its name; an iPhone HEIC photo is converted on the phone where it can be. ----
R("function ocrScale(file){",
  "/* v128: saving a file from Sorted (the adviser pack, all your cases, a calendar reminder). On a phone with a share sheet\n   (iPhone and Android, including Sorted added to the Home Screen) the file goes through the share sheet, where \"Save to\n   Files\" or the calendar can take it. Elsewhere it downloads; the link is kept for a minute so a \"Download?\" question\n   can be answered first. The message says what actually happened. */\nfunction saveFile(name,text,mime,what){\n  var f=null,blob=new Blob([text],{type:mime});\n  try{f=new File([blob],name,{type:mime})}catch(e){f=null}\n  var touch=false;try{touch=window.matchMedia&&window.matchMedia(\"(pointer:coarse)\").matches}catch(e){}\n  if(f&&touch&&navigator.canShare&&navigator.share){var can=false;try{can=navigator.canShare({files:[f]})}catch(e){}\n    if(can){navigator.share({files:[f],title:name}).then(function(){toast(what===\"cal\"?\"Sent to your phone. Choose your calendar to add it.\":\"Done. Choose “Save to Files” if you want to keep it on this phone.\")},function(err){if(err&&err.name===\"AbortError\")toast(\"Not saved.\");else saveDl(blob,name,what)});return}}\n  saveDl(blob,name,what);\n}\nfunction saveDl(blob,name,what){\n  try{var u=URL.createObjectURL(blob),a=document.createElement(\"a\");if(!(\"download\" in a)){window.open(u,\"_blank\");toast(\"Opened in a new tab. Use your browser’s share or save button to keep it.\");setTimeout(function(){URL.revokeObjectURL(u)},60000);return}\n    a.href=u;a.download=name;a.rel=\"noopener\";document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);a.remove()},60000);\n    toast(what===\"cal\"?\"Your phone or computer should offer to add it to your calendar. If it asks, choose Download, then open the file.\":\"If your browser asks, choose Download. The file goes to your Downloads (on iPhone, the Files app).\")}\n  catch(e){toast(\"Your browser didn’t allow the download. Use Copy instead.\")}\n}\nfunction ocrScale(file){");
R("case \"pack-download\":if(t){try{var pkb=new Blob([packText(t)],{type:\"text/plain;charset=utf-8\"}),pku=URL.createObjectURL(pkb),pka=document.createElement(\"a\");pka.href=pku;pka.download=\"Sorted - \"+home54Title(t).replace(/[\\\\\\/:*?\"<>|]+/g,\" \").replace(/\\s+/g,\" \").trim()+\".txt\";document.body.appendChild(pka);pka.click();setTimeout(function(){URL.revokeObjectURL(pku);pka.remove()},1000);toast(\"Downloaded. It’s on this phone only.\")}catch(e){toast(\"Your browser didn’t allow the download. Use Copy instead.\")}}break;",
  "case \"pack-download\":if(t){saveFile(\"Sorted - \"+home54Title(t).replace(/[\\\\\\/:*?\"<>|]+/g,\" \").replace(/\\s+/g,\" \").trim()+\".txt\",packText(t),\"text/plain;charset=utf-8\",\"pack\")}break;");
R("      var exb=new Blob([exL.join(\"\\n\")],{type:\"text/plain;charset=utf-8\"}),exu=URL.createObjectURL(exb),exa=document.createElement(\"a\");exa.href=exu;exa.download=\"Sorted - all my cases.txt\";document.body.appendChild(exa);exa.click();setTimeout(function(){URL.revokeObjectURL(exu);exa.remove()},1000);toast(\"Downloaded. It’s on this phone only.\")}catch(e){toast(\"Your browser didn’t allow the download. Use Copy instead.\")}break}",
  "      saveFile(\"Sorted - all my cases.txt\",exL.join(\"\\n\"),\"text/plain;charset=utf-8\",\"all\")}catch(e){toast(\"Your browser didn’t allow the download. Use Copy instead.\")}break}");
R("var bl=new Blob([icsText(cp)],{type:\"text/calendar\"}),an=document.createElement(\"a\");an.href=URL.createObjectURL(bl);an.download=\"sorted-reminder.ics\";document.body.appendChild(an);an.click();setTimeout(function(){URL.revokeObjectURL(an.href);an.remove()},1000);",
  "saveFile(\"sorted-reminder.ics\",icsText(cp),\"text/calendar\",\"cal\");");
R("  var isPdf=file.type===\"application/pdf\"||/\\.pdf$/i.test(file.name||\"\");\n  if(!isPdf&&!/^image\\//.test(file.type||\"\")){ocrStatus(\"That isn’t a picture or a PDF. Add a screenshot, a photo or a PDF.\",true);return}\n  if(/hei[cf]/i.test(file.type||\"\")||/\\.hei[cf]$/i.test(file.name||\"\")){ocrStatus(\"Sorted can’t read HEIC photos yet. Take a screenshot of the photo and add that, or set the camera to “Most compatible”.\",true);return}",
  "  var isPdf=file.type===\"application/pdf\"||/\\.pdf$/i.test(file.name||\"\");\n  /* v128: a file from Files, iCloud or Google Drive can arrive with no type; its name says what it is */\n  var isImg=/^image\\//.test(file.type||\"\")||(!file.type&&/\\.(?:jpe?g|png|gif|webp|bmp|tiff?|hei[cf])$/i.test(file.name||\"\"));\n  if(!isPdf&&!isImg){ocrStatus(\"That isn’t a picture or a PDF. Add a screenshot, a photo or a PDF.\",true);return}\n  if(/hei[cf]/i.test(file.type||\"\")||/\\.hei[cf]$/i.test(file.name||\"\")){\n    /* iPhone photos kept in Files are HEIC. Safari can open them, so Sorted converts the photo on the phone; where the\n       browser can't, it says so with a way out. */\n    ocrStatus(\"Opening the photo…\");\n    heicToCanvas(file).then(function(c){if(!c){ocrStatus(\"Sorted can’t read HEIC photos on this browser. Take a screenshot of the photo and add that, or set the camera to “Most compatible”.\",true);return}readPicture2(c,file,target)});return}\n  readPicture2(file,file,target);\n}\nfunction heicToCanvas(file){return new Promise(function(res){try{var u=URL.createObjectURL(file),im=new Image();im.onload=function(){try{var w=im.naturalWidth,h=im.naturalHeight,m=Math.max(w,h),k=m>2400?2400/m:1,c=document.createElement(\"canvas\");c.width=Math.max(1,Math.round(w*k));c.height=Math.max(1,Math.round(h*k));c.getContext(\"2d\").drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(w&&h?c:null)}catch(e){URL.revokeObjectURL(u);res(null)}};im.onerror=function(){URL.revokeObjectURL(u);res(null)};im.src=u}catch(e){res(null)}})}\nfunction readPicture2(src,file,target){\n  var isPdf=file.type===\"application/pdf\"||/\\.pdf$/i.test(file.name||\"\");");
R("  readImage(file,target,tok);\n}",
  "  readImage(src,target,tok);\n}");
R("var SORTED_V=\"v121\"",
  "var SORTED_V=\"v128\"");
fs.writeFileSync('public/index.html',s);
const EXPECT='ce8a0dfe7c21c5cc464d5b05f0193bbbc73344ba';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v128 ok',h(s),s.length);
