const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='7cde655a2e3d0b3158d440b79019b1be196a6ba1')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,80));s=s.split(a).join(b)}
// v79: richer consumer visual language. Behaviour and case state are unchanged.
R('</style>\n\n</head>',String.raw`/* v79 expressive visual system */
:root{
 --violet:#6D4CFF;--violet2:#4F39D9;--vsoft:#EEE9FF;
 --coral:#FF6B6B;--csoft:#FFE8E6;--aqua:#19B9C7;--asoft:#DDF8FA;
 --green:#24A36B;--gsoft:#E1F6EC;--amber:#E7A11A;--amsoft:#FFF1CE;
}
body{background:radial-gradient(circle at 8% 4%,color-mix(in srgb,var(--violet) 9%,transparent),transparent 28rem),radial-gradient(circle at 96% 18%,color-mix(in srgb,var(--coral) 7%,transparent),transparent 24rem),var(--paper)}
.bar{background:color-mix(in srgb,var(--paper) 88%,transparent);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);border-bottom:1px solid color-mix(in srgb,var(--rule) 70%,transparent)}
.mark{font-size:27px;letter-spacing:-.035em}.mark b{background:linear-gradient(135deg,var(--violet),#8F63FF 45%,var(--coral));-webkit-background-clip:text;background-clip:text;color:transparent}
.hero{position:relative;isolation:isolate;overflow:hidden;border:1px solid color-mix(in srgb,var(--violet) 20%,var(--rule));border-radius:28px;padding:26px 24px 22px;background:radial-gradient(circle at 86% 12%,color-mix(in srgb,var(--coral) 28%,transparent),transparent 30%),radial-gradient(circle at 5% 80%,color-mix(in srgb,var(--aqua) 18%,transparent),transparent 32%),linear-gradient(145deg,color-mix(in srgb,var(--sheet) 94%,var(--vsoft)),color-mix(in srgb,var(--sheet) 84%,var(--csoft)));box-shadow:0 24px 70px rgba(48,35,111,.14)}
.hero:before,.hero:after{content:"";position:absolute;z-index:-1;border-radius:50%;pointer-events:none}.hero:before{width:150px;height:150px;right:-72px;top:-68px;background:linear-gradient(145deg,color-mix(in srgb,var(--violet) 70%,white),color-mix(in srgb,var(--coral) 55%,white));opacity:.33}.hero:after{width:88px;height:88px;left:-36px;bottom:38px;background:linear-gradient(145deg,var(--aqua),var(--violet));opacity:.16}
.hero .eyebrow{color:color-mix(in srgb,var(--violet) 80%,var(--ink));font-weight:800}.hero .h1{font-size:clamp(38px,10vw,54px)}.hero .h1 em{background:linear-gradient(120deg,var(--violet),#8155FF 48%,var(--coral));-webkit-background-clip:text;background-clip:text;color:transparent}.hero-art{filter:drop-shadow(0 20px 26px rgba(67,46,129,.18));transform-origin:50% 70%}
.btn{border-radius:14px;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease,background .18s ease}.btn.primary{background:linear-gradient(135deg,var(--violet),var(--violet2));border-color:transparent;color:#fff;box-shadow:0 10px 24px rgba(109,76,255,.24)}.btn:not(.primary):not(.danger){background:color-mix(in srgb,var(--sheet) 92%,var(--vsoft));border-color:color-mix(in srgb,var(--violet) 28%,var(--rule))}.btn:hover{transform:translateY(-1px)}.btn.primary:hover{box-shadow:0 14px 30px color-mix(in srgb,var(--violet) 32%,transparent)}.btn:active{transform:translateY(0) scale(.985)}
.start{border-radius:18px;border-color:color-mix(in srgb,var(--violet) 26%,var(--rule));background:linear-gradient(145deg,var(--sheet),color-mix(in srgb,var(--sheet) 86%,var(--vsoft)));box-shadow:0 10px 28px rgba(43,35,91,.06);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.start:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--violet) 55%,var(--rule));box-shadow:0 16px 34px rgba(43,35,91,.11)}.start .go{color:var(--violet)}
.sheet,.check,.safety,.note,.promise,.case56-next,.case75-group,.cm-card,.pb-card,.pk-card{border-radius:18px}.sheet{border-color:color-mix(in srgb,var(--violet) 13%,var(--rule));box-shadow:0 10px 30px rgba(31,27,65,.055)}.note{background:linear-gradient(135deg,color-mix(in srgb,var(--sheet) 92%,var(--asoft)),color-mix(in srgb,var(--sheet) 94%,var(--vsoft)))}.check{border-color:color-mix(in srgb,var(--aqua) 65%,var(--violet));background:linear-gradient(135deg,var(--asoft),color-mix(in srgb,var(--asoft) 65%,var(--vsoft)))}.check .tag{background:linear-gradient(135deg,var(--aqua),var(--violet));color:#fff}
.chip{border-color:color-mix(in srgb,var(--violet) 30%,var(--rule));background:color-mix(in srgb,var(--sheet) 94%,var(--vsoft));transition:transform .16s ease,background .16s ease,border-color .16s ease}.chip:hover{transform:translateY(-1px);border-color:var(--violet)}.chip[aria-pressed="true"]{background:linear-gradient(135deg,var(--violet),var(--violet2));border-color:transparent;color:#fff}
input[type=text],input[type=date],input[type=time],textarea{border-radius:14px;border-color:color-mix(in srgb,var(--violet) 22%,var(--ink-2));background:color-mix(in srgb,var(--sheet) 97%,var(--vsoft))}input:focus,textarea:focus{border-color:var(--violet);box-shadow:0 0 0 4px color-mix(in srgb,var(--violet) 16%,transparent)}
.home54-folder{border-color:color-mix(in srgb,var(--violet) 55%,var(--lav));background:linear-gradient(145deg,#F3EEFF,#FFDCD8)}.home54-folder:before{border-color:color-mix(in srgb,var(--violet) 55%,var(--lav));background:#E8DEFF}.home54-folder:after{background:var(--violet);box-shadow:0 8px 0 color-mix(in srgb,var(--coral) 70%,transparent),0 16px 0 color-mix(in srgb,var(--aqua) 60%,transparent)}.home54-clock{border-color:var(--coral);background:linear-gradient(145deg,#fff,var(--csoft));box-shadow:0 8px 22px rgba(255,107,107,.22)}.home54-count{background:linear-gradient(135deg,var(--violet),var(--coral));color:#fff;border-color:var(--sheet)}
.home44-spot{position:relative;overflow:hidden;border:1px solid color-mix(in srgb,var(--coral) 30%,var(--violet));background:radial-gradient(circle at 90% 8%,color-mix(in srgb,var(--coral) 24%,transparent),transparent 30%),radial-gradient(circle at 8% 100%,color-mix(in srgb,var(--aqua) 15%,transparent),transparent 32%),linear-gradient(140deg,color-mix(in srgb,var(--sheet) 93%,var(--vsoft)),color-mix(in srgb,var(--sheet) 84%,var(--csoft)));box-shadow:0 22px 54px rgba(59,40,128,.14)}.home44-spot:after{content:"";position:absolute;right:-46px;bottom:-52px;width:130px;height:130px;border-radius:50%;background:linear-gradient(145deg,color-mix(in srgb,var(--coral) 60%,white),color-mix(in srgb,var(--violet) 66%,white));opacity:.16;pointer-events:none}
.home44-section.needs .h2{color:color-mix(in srgb,var(--coral) 78%,var(--ink))}.home44-section.waiting .h2{color:color-mix(in srgb,var(--violet) 74%,var(--ink))}.home44-section.waiting .home44-section-head .h2:before{background:var(--violet);box-shadow:0 0 0 5px color-mix(in srgb,var(--violet) 14%,transparent)}
.home44-row{border-radius:18px;border-color:color-mix(in srgb,var(--violet) 14%,var(--rule));box-shadow:0 9px 24px rgba(31,27,65,.055)}.home44-row.needs{background:linear-gradient(105deg,color-mix(in srgb,var(--csoft) 66%,var(--sheet)),var(--sheet) 42%);border-left-color:var(--coral)}.home44-row.needs:before{background:var(--coral);box-shadow:0 0 0 5px color-mix(in srgb,var(--coral) 16%,transparent)}.home44-row.waiting{background:linear-gradient(105deg,color-mix(in srgb,var(--vsoft) 70%,var(--sheet)),var(--sheet) 44%)}.home44-row.waiting:before{background:var(--violet);box-shadow:0 0 0 5px color-mix(in srgb,var(--violet) 15%,transparent)}.home44-row.done{background:linear-gradient(105deg,color-mix(in srgb,var(--gsoft) 58%,var(--sheet)),var(--sheet) 52%);opacity:.9}.home44-row.done:before{background:var(--green)}.home44-row:hover{border-color:color-mix(in srgb,var(--violet) 40%,var(--rule));box-shadow:0 15px 32px rgba(45,34,102,.11)}.home44-pill{border-radius:999px;background:color-mix(in srgb,var(--vsoft) 90%,var(--sheet));color:var(--violet2);border:1px solid color-mix(in srgb,var(--violet) 22%,transparent)}.home44-new{border-radius:18px;border:1.5px dashed color-mix(in srgb,var(--violet) 35%,var(--rule));background:linear-gradient(135deg,color-mix(in srgb,var(--sheet) 94%,var(--asoft)),color-mix(in srgb,var(--sheet) 92%,var(--vsoft)))}
.case75-title-ref{display:inline-flex;width:max-content;padding:4px 9px;border-radius:999px;background:color-mix(in srgb,var(--vsoft) 82%,var(--sheet));color:var(--violet2);border:1px solid color-mix(in srgb,var(--violet) 18%,transparent)}.case56-next{position:relative;overflow:hidden;border:1px solid color-mix(in srgb,var(--coral) 28%,var(--violet));background:radial-gradient(circle at 94% 2%,color-mix(in srgb,var(--coral) 22%,transparent),transparent 34%),linear-gradient(140deg,color-mix(in srgb,var(--sheet) 91%,var(--csoft)),color-mix(in srgb,var(--sheet) 91%,var(--vsoft)));box-shadow:0 18px 44px rgba(52,39,111,.11)}.case56-next.hot{border-color:color-mix(in srgb,var(--coral) 55%,var(--violet));box-shadow:0 20px 50px rgba(255,107,107,.18)}.case56-overline{color:color-mix(in srgb,var(--violet) 72%,var(--ink-2));font-weight:800}
.promise{border-color:color-mix(in srgb,var(--amber) 58%,var(--yellow-edge));background:linear-gradient(145deg,color-mix(in srgb,var(--amsoft) 78%,var(--sheet)),color-mix(in srgb,var(--yellow) 72%,var(--sheet)));box-shadow:0 14px 34px rgba(153,105,18,.09)}.promise.pink{border-color:color-mix(in srgb,var(--coral) 58%,var(--pink-edge));background:linear-gradient(145deg,var(--csoft),color-mix(in srgb,var(--pink) 72%,var(--sheet)))}.case75-promise-context{border:1px solid color-mix(in srgb,var(--amber) 30%,var(--rule));border-radius:16px;padding:14px 15px;background:linear-gradient(135deg,color-mix(in srgb,var(--amsoft) 72%,var(--sheet)),color-mix(in srgb,var(--sheet) 88%,var(--vsoft)))}
.case75-group{overflow:hidden;border:1px solid color-mix(in srgb,var(--violet) 16%,var(--rule));background:color-mix(in srgb,var(--sheet) 96%,var(--vsoft));box-shadow:0 10px 28px rgba(33,28,72,.05)}.case75-group>summary{padding:16px 17px}.case75-group[open]>summary{background:linear-gradient(120deg,color-mix(in srgb,var(--vsoft) 75%,var(--sheet)),color-mix(in srgb,var(--asoft) 38%,var(--sheet)))}.case75-happened{border-left:4px solid var(--aqua)}.case75-tools{border-left:4px solid var(--violet)}.cm-card{border-color:color-mix(in srgb,var(--aqua) 35%,var(--rule));background:radial-gradient(circle at 95% 5%,color-mix(in srgb,var(--aqua) 15%,transparent),transparent 32%),var(--sheet)}.shared-banner{border-radius:16px;background:linear-gradient(135deg,var(--violet),var(--aqua));color:#fff;box-shadow:0 12px 30px rgba(25,185,199,.18)}
:root[data-theme="dark"]{--paper:#0B0D18;--sheet:#15182A;--ink:#F5F4FF;--ink-2:#B9BBD1;--rule:#33384F;--carbon:#AFA2FF;--carbon-ink:#0C0D16;--carbon-soft:#242344;--vsoft:#28234D;--csoft:#40242B;--asoft:#16383D;--gsoft:#18352A;--amsoft:#3A301C}:root[data-theme="dark"] .hero{background:radial-gradient(circle at 88% 8%,rgba(255,100,112,.18),transparent 31%),radial-gradient(circle at 5% 82%,rgba(30,190,204,.12),transparent 34%),linear-gradient(145deg,#18192D,#201A35);box-shadow:0 24px 70px rgba(0,0,0,.38)}:root[data-theme="dark"] .home44-spot{background:radial-gradient(circle at 90% 8%,rgba(255,107,107,.18),transparent 32%),radial-gradient(circle at 8% 100%,rgba(25,185,199,.12),transparent 32%),linear-gradient(140deg,#191B31,#241B36)}:root[data-theme="dark"] .home44-row.needs{background:linear-gradient(105deg,#2A1D29,#171A2B 48%)}:root[data-theme="dark"] .home44-row.waiting{background:linear-gradient(105deg,#211E3A,#171A2B 50%)}:root[data-theme="dark"] .home44-row.done{background:linear-gradient(105deg,#15281F,#171A2B 52%)}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--paper:#0B0D18;--sheet:#15182A;--ink:#F5F4FF;--ink-2:#B9BBD1;--rule:#33384F;--carbon:#AFA2FF;--carbon-ink:#0C0D16;--carbon-soft:#242344;--vsoft:#28234D;--csoft:#40242B;--asoft:#16383D;--gsoft:#18352A;--amsoft:#3A301C}}
@media (prefers-reduced-motion:no-preference){.hero-art{animation:v79Float 6s ease-in-out infinite}.hero:before{animation:v79Orb 8s ease-in-out infinite}.home44-spot:after{animation:v79Orb 7s ease-in-out infinite reverse}.btn.primary{background-size:160% 160%;animation:v79Button 7s ease-in-out infinite}}
@media (prefers-reduced-motion:reduce){.hero-art,.hero:before,.home44-spot:after,.btn.primary{animation:none!important;transition:none!important}}
@keyframes v79Float{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@keyframes v79Orb{0%,100%{transform:translate3d(0,0,0) scale(1)}50%{transform:translate3d(-8px,10px,0) scale(1.08)}}@keyframes v79Button{0%,100%{background-position:0 50%}50%{background-position:100% 50%}}
@media (max-width:520px){.hero{padding:22px 18px 19px;border-radius:23px}.hero .h1{font-size:clamp(36px,11vw,48px)}.case56-next,.case75-group,.sheet{border-radius:16px}.home44-row{border-radius:16px}}
</style>

</head>`);
fs.writeFileSync('public/index.html',s);
const EXPECT='0000000000000000000000000000000000000000';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v79 ok',h(s),s.length);