const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='2bb8694b88723279b084a46e6852a610010b57a6')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v165: a photo of the appliance itself is progress, not a failed scan (Baldwin's iPhone, 10 October 2026: he
// photographed the machine, not its label, and saw "Sorted couldn't read that photo"). Sorted reads words on the phone; it
// doesn't recognise machines from their shape, and says so. A photo with no make, model or serial now asks for the rating
// label, says where it usually is for each kind of thing, lets the person say what it is, and offers typing or carrying
// on without the model. The message is said once (the status line no longer repeats it).
R(`  if(!has)return h+'<h2 class="h3" id="prod161-h" tabindex="-1">Sorted couldn’t read that photo</h2><p role="alert" style="margin:0">It couldn’t find a make, model or serial number. Nothing has been saved.</p><div class="row" style="flex-wrap:wrap">'+prodPick161("Retake photo",true," primary")+prodPick161("Choose another photo")+'</div><button type="button" class="link" data-a="prod161-type" style="align-self:flex-start">Type the make and model</button>'+prodWhere161(p)+st+'</section>';`,
  `  if(!has)return h+'<h2 class="h3" id="prod161-h" tabindex="-1">Now photograph the label</h2><p role="status" style="margin:0">Sorted didn’t find a make, model or serial number in that photo. It reads the words on a label, not the machine itself. Nothing has been saved.</p><p style="margin:0">The rating label is a small sticker or plate with the model number on it. Get close so it fills the photo, in good light.</p><div class="row" style="flex-wrap:wrap">'+prodPick161("Photograph the label",true," primary")+prodPick161("Choose a photo")+'</div>'+prodWhere161(p,true)+'<button type="button" class="link" data-a="prod161-type" style="align-self:flex-start">Type the make and model</button><form class="stack-s" data-f="prod161" data-m="ok">'+prodCats161(r)+'<button class="btn" type="submit" style="align-self:flex-start">Continue without the label</button></form>'+st+'</section>';`);
R(`function prodWhere161(p){return '<button type="button" class="link" data-a="prod161-where" aria-expanded="'+(p&&p.where?"true":"false")+'" style="align-self:flex-start">Show me where to look</button>'+(p&&p.where?'<p class="note" style="margin:0">The label is often inside the door or lid, on the back, or underneath. Look for the words Model, Type or E-Nr. A serial number is often marked S/N.</p>':'')}`,
  `function prodWhere161(p,open){var on=open||(p&&p.where);return (open?'':'<button type="button" class="link" data-a="prod161-where" aria-expanded="'+(on?"true":"false")+'" style="align-self:flex-start">Show me where to look</button>')+(on?'<div class="note stack-s" style="margin:0"><p style="margin:0"><strong>Where the label usually is</strong></p><ul style="margin:0;padding-left:1.1em"><li>Washing machine or tumble dryer: around the inside of the door</li><li>Dishwasher: on the edge of the door</li><li>Fridge or freezer: inside, on a side wall</li><li>Oven or cooker: on the door frame</li><li>Vacuum cleaner: underneath, or behind the bin</li><li>Printer, router or coffee machine: on the back or underneath</li></ul><p style="margin:0">Look for the words Model, Type or E-Nr. A serial number is often marked S/N.</p></div>':'')}`);
R('else{p.fail=true;p.msg="Sorted couldn’t read that photo. Nothing has been saved."}','else{p.fail=true;p.msg=prodHasFact161(rec)||["brand","model","serial","category"].some(function(k){return PR161.candidate(rec,k)})?"Sorted couldn’t read that photo. The details below are from before.":"Photo read on your phone."}');
s=s.split('SORTED_V="v164"').join('SORTED_V="v165"');
fs.writeFileSync('public/index.html',s);
const EXPECT='eeb5932006e2ee9a4af015615f49241865a4a3da';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v165 ok',h(s),s.length);
