const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='e9350d1a71bade80f173e98d704aa568532f4f6d')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v126 (the remaining-pages review, public pages): "Keep everyday admin moving." with one main action, three
// common problems, one worked example and the full catalogue behind Browse more; Help questions first, grouped; a
// shorter How it works; About leads with why Sorted exists; a copyable contact address; Privacy and Terms point at
// the real places and describe all of Sorted. ----
R("<section class=\"hero\"><p class=\"eyebrow\">Life admin has a habit of piling up. Sorted helps you keep it moving.</p><h1 class=\"h1\">They said Tuesday.<br><em>Sorted remembers Tuesday.</em></h1><p class=\"lede\">Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Sorted shows what needs you, what you’re waiting for and when to follow up.</p><p class=\"hero-kinds\">Refunds · repairs · parking notices · claims · important calls · moving home</p>'+('<a class=\"btn primary hero-cta\" href=\"#start\" style=\"align-self:flex-start\">Get something sorted →</a>'+'<img class=\"hero-art\" src=\"/art/hero-case.webp\" width=\"640\" height=\"410\" alt=\"A case folder with a washing machine, a clock and a phone\" fetchpriority=\"high\">'+'<p class=\"hero-note\">You don’t have to keep remembering whether they got back to you. Run by one person in the UK; start without an account. <a class=\"link\" href=\"#how\">See how it works</a>.</p>')+'</section>'+landingExamples();",
  "<section class=\"hero hero126\"><h1 class=\"h1\">Keep everyday admin moving.</h1><p class=\"lede\">Parking notices, delayed refunds, repairs and confusing letters. Keep the details together, prepare your next step and track what happens.</p><div class=\"hero-start stack-s\"><button type=\"button\" class=\"btn primary hero-cta\" data-cap82=\"other\">Start with your problem</button><p class=\"hero-sub\">Describe it in your own words, or add a document.</p><button type=\"button\" class=\"link hero-seeex\" data-a=\"see-example\">See an example</button></div><p class=\"hero-quick-l\" id=\"hq126\">Or start from a common problem</p><div class=\"hero-quick\" role=\"group\" aria-labelledby=\"hq126\"><button type=\"button\" class=\"chip\" data-cap95=\"parking\">Parking notice</button><button type=\"button\" class=\"chip\" data-cap95=\"refund\">Missing refund</button><button type=\"button\" class=\"chip\" data-cap95=\"landlord\">Repair problem</button></div></section>'+landing126();");
R("function landingExamples(){",
  "/* v126: under the hero, one short worked example (labelled), then the full catalogue of ways in behind \"Browse more\". The\n   chooser script puts its panel inside #browse126. */\nfunction landing126(){\n  return '<section class=\"sheet stack-s ex126\" id=\"example126\" aria-labelledby=\"ex126-h\"><p class=\"eyebrow\" id=\"ex126-h\">Example</p><p><strong>A refund that hasn’t arrived.</strong> “Currys said my £89 refund would arrive by Friday 9 October, order 445566.”</p><p>Sorted keeps who, how much, the order number and the date. On Saturday the case is at the top of Home and asks “Has the money arrived?” If not, it gets a message ready with what they said and when.</p><a class=\"link\" href=\"#how\" style=\"align-self:flex-start\">See the whole example</a></section>'+\n  '<details class=\"browse126\" id=\"browse126\"><summary><span>Browse more ways to start</span><span class=\"muted\" style=\"font-size:14px\">Repairs, calls, letters, renewals, moving home and more</span></summary></details>'+\n  '<p class=\"muted landing126-small\">You don’t have to keep remembering whether they got back to you. Run by one person in the UK. Start without an account. <a class=\"link\" href=\"#privacy\">How your data is handled</a></p>';\n}\nfunction landingExamples(){");
R("hero.insertAdjacentHTML('afterend',panel('cap82-landing',false));",
  "{var bw126=document.querySelector('#browse126');if(bw126)bw126.insertAdjacentHTML('beforeend',panel('cap82-landing',false));else hero.insertAdjacentHTML('afterend',panel('cap82-landing',false))}");
R("if(hero.nextElementSibling!==landing)hero.insertAdjacentElement('afterend',landing);",
  "if(!landing.closest('details')&&hero.nextElementSibling!==landing)hero.insertAdjacentElement('afterend',landing);");
R("content=\"They said Tuesday. Sorted remembers Tuesday. Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Sorted shows what needs you, what you’re waiting for and when to follow up.\"",
  "content=\"Keep everyday admin moving. Parking notices, delayed refunds, repairs and confusing letters. Keep the details together, prepare your next step and track what happens.\"");
R(".cap85-public .hero .cap85-top-cta{display:inline-flex;align-self:flex-start;margin-top:4px}",
  ".cap85-public .hero .cap85-top-cta{display:inline-flex;align-self:flex-start;margin-top:4px}\n.hero126 .h1{max-width:none}\n.hero126 .hero-start{margin-top:6px}\n.hero126 .hero-sub{margin:0;font-size:15px;color:var(--ink-2)}\n.hero126 .hero-seeex{align-self:flex-start}\n.hero126 .hero-quick{display:flex;flex-wrap:wrap;gap:8px;margin-top:4px}\n.hero126 .hero-quick .chip{min-height:44px;width:auto;flex:0 0 auto;align-self:auto;font-size:15px;padding:8px 14px}\n.hero126 .hero-quick-l{margin:6px 0 0;font-size:14px;font-weight:700;color:var(--ink-2)}\n.browse126{margin:12px 0}\n.browse126>summary{cursor:pointer;min-height:44px;padding:12px 16px;border:1px solid var(--rule);border-radius:14px;list-style:none;display:flex;flex-direction:column;gap:2px;font-weight:700;background:var(--sheet)}\n.browse126>summary::-webkit-details-marker{display:none}\n.browse126[open]>summary{margin-bottom:12px}\n.ex126{margin-top:12px}\n.landing126-small{font-size:14px;margin:8px 0 0}");
R("(home?'Life admin has a habit of piling up. Sorted helps you keep it moving.':'What do you need to get sorted?')",
  "(home?'Keep everyday admin moving.':'What do you need to get sorted?')");
R("(home?'Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Choose what’s happening and Sorted works out the next move.':'Choose what’s happening and Sorted works out the next move.')",
  "(home?'Parking notices, delayed refunds, repairs and confusing letters. Choose what’s happening, or tell Sorted in your own words.':'Choose what’s happening, or tell Sorted in your own words.')");
R("want=has?'What do you need?':'Life admin has a habit of piling up. Sorted helps you keep it moving.'",
  "want=has?'What do you need?':'Keep everyday admin moving.'");
R("[\"What is Sorted for?\",\"Life admin has a habit of piling up. Sorted helps you keep it moving. ",
  "[\"What is Sorted for?\",\"Sorted keeps everyday admin moving. ");
R("if(location.hash===\"#help\")return h+sitePage(\"Help\",howBlock()+helpBlock()+pageDate(\"Help\"))",
  "if(location.hash===\"#help\")return h+sitePage(\"Help\",helpBlock()+'<p><a class=\"link\" href=\"#how\">How Sorted works, with an example</a></p>'+pageDate(\"Help\"))");
R("function helpBlock(){\n  return '<section class=\"sheet stack-s acct112-faq\"><p class=\"h3\">Questions people ask</p>'+HELP_FAQ.map(function(q){return '<details class=\"acct112-q\"><summary>'+esc(q[0])+'</summary><p>'+esc(q[1])+'</p></details>'}).join(\"\")+'</section>';\n}",
  "/* v126: the questions in four groups */\nvar HELP_GROUPS=[[\"Starting\",/^(?:What is Sorted for|Who is it useful for|How is it different|Does Sorted deal with everything|What if I don’t know what to do next|Can I track things I need to do myself|Can I organise an insurance claim|Can I use it for moving home|How do I start|What should I record|Can I edit a case|Can I finish a case|Does Sorted contact companies|What does Sorted cost)/],[\"Documents\",/^(?:Can I add a screenshot|Can I use Sorted for a parking notice|What information should I avoid)/],[\"Reminders\",/^(?:How do reminders work|What if they haven’t given me a date|What if they change the date|Can I change or stop a reminder)/],[\"Account and your data\",/./]];\nfunction helpBlock(){\n  var used={},h='<section class=\"sheet stack-s acct112-faq\"><h2 class=\"h3\" style=\"margin:0\">Questions people ask</h2>';\n  HELP_GROUPS.forEach(function(g){var qs=HELP_FAQ.filter(function(q){return !used[q[0]]&&g[1].test(q[0])});if(!qs.length)return;qs.forEach(function(q){used[q[0]]=1});h+='<h3 class=\"help126-g\">'+esc(g[0])+'</h3>'+qs.map(function(q){return '<details class=\"acct112-q\"><summary>'+esc(q[0])+'</summary><p>'+esc(q[1])+'</p></details>'}).join(\"\")});\n  return h+'</section>';\n}");
R("var steps=[[\"Tell Sorted what is happening.\",\"Say it in your own words, or add the useful text from a message, a photo or a PDF. Sorted says what it understood, and asks whose move it is if that isn’t clear.\"],[\"Choose the next step.\",\"Confirm what the other side promised and by when, record something you need to do, or pick a date to follow up. Nothing is saved until you press Start. Sorted doesn’t turn an uncertain suggestion into a confirmed fact until you confirm it.\"],[\"Keep the matter moving.\",\"When a date falls due the case comes to the top of Home and asks what happened. Record replies, get a chase ready, note a new date, and finish the case when it’s done.\"]];",
  "var steps=[[\"Tell Sorted what is happening.\",\"In your own words, or from a message, photo or PDF.\"],[\"Choose the next step.\",\"What they promised, something you need to do, or a date to follow up. Sorted doesn’t turn an uncertain suggestion into a confirmed fact until you confirm it.\"],[\"Keep it moving.\",\"When a date falls due, the case comes to the top of Home and asks what happened.\"]];");
R("  '<p>Sorted is built and run by Baldwin Thompson-Addo in London.</p>'+\n  '<p>Baldwin works in data protection and information rights. He has spent more than seven years in regulated financial services, information security and privacy, including over four years in insurance privacy work: handling people’s requests for their own data, keeping case logs, tracking statutory deadlines and making sure every decision is recorded. He holds an MSc in Information Security Management from Northumbria University and a first-class BSc in Cybersecurity from the University of West London.</p>'+\n  '<p>That work is about keeping track of who owes what, by when, with a record that stands up later. Sorted gives you the same for your own everyday problems: the refund, the repair, the callback someone promised.</p>'+",
  "  '<p><strong>Why it exists.</strong> Everyday admin rarely finishes in one go. A refund, a repair or a parking notice can take weeks of calls, emails and dates, and it’s easy to lose track of who promised what. Sorted keeps it in one place, so you can see what needs you and when to follow up.</p>'+\n  '<p><strong>Who runs it.</strong> Baldwin Thompson-Addo, in London. He works in data protection, where keeping an accurate record of who owes what, by when, is the job. He holds an MSc in Information Security Management and a first-class BSc in Cybersecurity.</p>'+");
R("function contactBlock(){return '<section class=\"sheet stack-s\" id=\"contact-block\"><p class=\"h3\">Contact and problems</p><p>Email <a class=\"link\" href=\"mailto:kofiniiakwei@gmail.com\">kofiniiakwei@gmail.com</a>. Say what you were trying to do, what happened and any message you saw; leave out case details you don’t need to share. You’ll get a reply within 10 working days.</p>'+reportLink(null)+'</section>'}",
  "function contactBlock(){return '<section class=\"sheet stack-s\" id=\"contact-block\"><p class=\"h3\">Contact and problems</p><p>Email <a class=\"link\" href=\"mailto:kofiniiakwei@gmail.com\">kofiniiakwei@gmail.com</a>. Say what you were trying to do, what happened and any message you saw; leave out case details you don’t need to share. You’ll get a reply within 10 working days.</p><div class=\"row contact126\"><input type=\"text\" id=\"contact-addr\" readonly value=\"kofiniiakwei@gmail.com\" aria-label=\"Sorted’s email address\"><button type=\"button\" class=\"btn\" data-a=\"copy-contact\">Copy the address</button></div><p class=\"muted\" style=\"margin:0;font-size:15px\">If tapping the address or “Report a problem” doesn’t open an email app, copy the address and paste it into any email service you use.</p>'+reportLink(null)+'</section>'}");
R("    case \"keep-go\":",
  "    case \"see-example\":{var ex126=$(\"#example126\");if(ex126){ex126.setAttribute(\"tabindex\",\"-1\");ex126.scrollIntoView({block:\"start\"});try{ex126.focus({preventScroll:true})}catch(e){}}break}\n    case \"copy-contact\":{var ca126=$(\"#contact-addr\");try{navigator.clipboard.writeText(\"kofiniiakwei@gmail.com\").then(function(){toast(\"Address copied\")},function(){if(ca126){ca126.focus();ca126.select()}})}catch(e){if(ca126){ca126.focus();ca126.select()}}break}\n    case \"keep-go\":");
R("You can turn them off in “Your data”; that applies to the phone you’re using.",
  "You can turn them off in Account, under Settings; that applies to the phone you’re using.");
R("You can copy or delete everything yourself in “Your data”.",
  "You can copy or delete everything yourself in Account: “Download my cases” and “Delete my account”.");
R("<p><strong>What Sorted is.</strong> A place to keep track of what someone else has promised you, with reminders when it’s due.",
  "<p><strong>What Sorted is.</strong> A place to keep everyday admin moving: what someone has promised you, things you need to do yourself, documents such as parking notices and letters, and renewals, with reminders when something is due.");
R(".u117 dd{margin:0;overflow-wrap:anywhere}",
  ".u117 dd{margin:0;overflow-wrap:anywhere}\n.help126-g{margin:14px 0 2px;font-size:17px}\n.contact126{gap:8px;flex-wrap:wrap;align-items:center}\n.contact126 input{flex:1 1 200px;min-height:44px;font:inherit;padding:8px 10px;border:1px solid var(--rule);border-radius:10px;background:var(--sheet);color:var(--ink)}");
fs.writeFileSync('public/index.html',s);
const EXPECT='636142b116aeb4e38d147367f97be60e8aeca61a';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v126 ok',h(s),s.length);
