const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='c55d8ccadcead6b3aa7b41b2f78a4806a5cdc89e')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v104: show your move to someone you live with. The existing helper link, pointed at the move: its steps and,
// for each case in it, one status line; it updates when a case in the move changes; read-only; switch it off any
// time. Step records moment_item share (link, copy, whatsapp, off); share_seen counts opens, never who. ----
R("function shareCard(t){\n  var f=t.fix||{}",
  "/* v104: a move shared with someone you live with. Only the steps and, for each case in the move, its name and one\n   status line (who you're waiting on, when, the ref). Never other cases, never what's inside a case. */\nfunction momShareCard(m){\n  var r=momRows(m),one=function(x,grp){var it=x.it||{};\n    if(x.c)return [String(x.l===home54Title(x.c)?x.l:x.l+\": \"+home54Title(x.c)).slice(0,140),momCaseLine(x.c).replace(/^Needs you\\b/,\"Needs doing\").slice(0,140),\"case\"];\n    var ln=grp===\"done\"?\"Done\":x.st===\"contacted\"?\"In touch\"+(x.who?\" with \"+x.who:\"\"):it.arr?(it.opt?\"Optional\":\"To arrange\"):(it.opt?\"If needed\":\"Yours to do\");\n    if((grp===\"coming\"||grp===\"consider\")&&x.from)ln+=\" · from \"+pkDayLabel(x.from);\n    return [String(x.l).slice(0,140),ln,it.arr?\"arr\":\"own\"]};\n  var g=[[\"Needs doing\",r.needs,\"needs\"],[\"Waiting\",r.waiting,\"waiting\"],[\"Expected\",r.coming,\"coming\"],[\"Worth considering\",r.consider,\"consider\"],[\"Done\",r.done,\"done\"]]\n    .filter(function(x){return x[1].length}).map(function(x){return [x[0],x[2],x[1].map(function(y){return one(y,x[2])})]});\n  return {v:3,k:\"moment\",s:nowIso(),t:m.title,d:m.date,g:g};\n}\nfunction momShareSync(m){if(m&&m.shareToken)sb.from(\"shares\").update({card:shareCard(m)}).eq(\"task_id\",m.id).then(function(){},function(){})}\nfunction shareCard(t){\n  if(t.kind===\"moment\")return momShareCard(t);\n  var f=t.fix||{}");
R("      if(t.shareToken)sb.from(\"shares\").update({card:shareCard(t)}).eq(\"task_id\",t.id).then(function(){});\n",
  "      if(t.shareToken)sb.from(\"shares\").update({card:shareCard(t)}).eq(\"task_id\",t.id).then(function(){});\n      if(t.momentId&&t.kind!==\"moment\")momShareSync(momOf(t.momentId));\n");
R("h+=momGroup(m,\"Done\",r.done,\"done\");",
  "h+=momGroup(m,\"Done\",r.done,\"done\");h+=momShareBlock(m);");
R("function momGroup(m,title,rows,grp,note){",
  "function momShareBlock(m){\n  var on=!!m.shareToken,h='<details class=\"case56-fold cap104-share\"'+(on||S.view.copyText?' open':'')+'><summary><span>Show this move to someone you live with</span><span class=\"case56-summary-note\">'+(on?\"Shared\":\"Only you can see it\")+'</span></summary><div class=\"case56-fold-body stack-s\">';\n  h+='<p>They get a link that shows where your move is up to and updates by itself. They can’t change anything.</p><p class=\"muted case56-small\">They see the steps and, for each case in this move, its name, who you’re waiting on, the date and the reference. Not your other cases, and not what’s inside each case. The link stops after 30 days without a change, or when you switch it off.</p>';\n  h+='<button class=\"btn block\" data-a=\"mom-share\">'+(on?\"Copy the link again\":\"Copy a link for them\")+'</button>';\n  if(on&&S.shareBusy!==m.id){var wm=\"I’m keeping track of our move on Sorted. This link shows where it’s up to: \"+location.origin+\"/?share=\"+m.shareToken;h+='<a class=\"btn block wa\" data-a=\"mom-wa\" href=\"https://wa.me/?text='+encodeURIComponent(wm)+'\" target=\"_blank\" rel=\"noopener\">Send the link on WhatsApp</a><button class=\"link\" data-a=\"mom-unshare\" style=\"text-align:left\">Switch the link off</button>'}\n  if(S.view.copyText)h+='<textarea class=\"copybox\" id=\"copyfallback\" readonly>'+esc(S.view.copyText)+'</textarea><p class=\"muted case56-small\">Copy this by hand. Your browser blocked the copy button.</p>';\n  return h+'</div></details>';\n}\nfunction momGroup(m,title,rows,grp,note){");
R("    case \"mom-link\":{",
  "    case \"mom-share\":{var sm=momOf(S.view.id);if(sm&&S.shareBusy!==sm.id){var sfresh=!sm.shareToken;if(sfresh){var srb=new Uint8Array(24);crypto.getRandomValues(srb);sm.shareToken=b64u(srb)}\n      var surl=location.origin+\"/?share=\"+sm.shareToken;\n      if(!sfresh){copy(surl,\"Link copied. Send it to them.\");momShareSync(sm);momItemTrack(sm,\"share\",\"copy\")}\n      else{sm._dirty=true;save();S.shareBusy=sm.id;render();\n        sb.from(\"shares\").insert({token:sm.shareToken,task_id:sm.id,card:shareCard(sm)}).then(function(r){S.shareBusy=null;if(r.error){toast(\"Couldn’t create the link. Try again.\");delete sm.shareToken;sm._dirty=true;save();render();return}momItemTrack(sm,\"share\",\"link\");copy(surl,\"Link copied. Send it to them.\");render()},function(){S.shareBusy=null;toast(\"Couldn’t create the link. Check your connection.\");delete sm.shareToken;sm._dirty=true;save();render()})}}break}\n    case \"mom-wa\":{var wmm=momOf(S.view.id);if(wmm&&wmm.shareToken){momShareSync(wmm);momItemTrack(wmm,\"share\",\"whatsapp\")}break}\n    case \"mom-unshare\":{var um=momOf(S.view.id);if(um&&um.shareToken){sb.from(\"shares\").delete().eq(\"task_id\",um.id).then(function(r){if(r&&r.error){toast(\"Couldn’t switch the link off. Try again.\");return}delete um.shareToken;um._dirty=true;momItemTrack(um,\"share\",\"off\");save();render();toast(\"Link switched off\")},function(){toast(\"Couldn’t switch the link off. Check your connection.\")})}break}\n    case \"mom-link\":{");
R("  if(!c){return h+'<p class=\"h3\">This link doesn’t open a case.</p>",
  "  if(c&&c.k===\"moment\")return h+sharedMoment(c)+'</main>';\n  if(!c){return h+'<p class=\"h3\">This link doesn’t open a case.</p>");
R("function viewShared(){",
  "function sharedMoment(c){\n  var at=new Date(S.sharedAt||c.s),dd=Math.round((new Date(c.d+\"T12:00:00\")-new Date(ymdL(new Date())+\"T12:00:00\"))/864e5);\n  var h='<p class=\"shared-banner\">Someone shared their move so you can see where it’s up to. You can look, but not change anything. It updates by itself. Last change: <span class=\"mono\">'+esc(fmtDay(at)+\", \"+fmtTime(at))+'</span>.</p>';\n  h+='<section class=\"stack-s cap99\"><p class=\"eyebrow\">Life moment</p><h1 class=\"h1\">'+esc(c.t||\"Moving home\")+'</h1><p class=\"cap99-date\">'+esc(pkDayLabel(c.d))+' · '+esc(dd===0?\"Moving today\":dd>0?(dd===1?\"Tomorrow\":\"In \"+dd+\" days\"):(dd===-1?\"Moved yesterday\":\"Moved \"+(-dd)+\" days ago\"))+'</p></section>';\n  (c.g||[]).forEach(function(g){h+='<section class=\"stack-s cap99 cap99-grp cap99-'+esc(g[1])+'\"><h2 class=\"h3\">'+esc(g[0])+' <span class=\"home44-count\">'+g[2].length+'</span></h2>'+g[2].map(function(x){\n    return '<div class=\"cap99-item'+(x[2]===\"case\"?' cap99-case cap103-big':x[2]===\"arr\"?' cap103-arr':' cap99-compact cap103-own')+'\">'+(x[2]===\"case\"?'<p class=\"cap99-kind\">Tracked case</p>':'')+'<p class=\"cap99-t\">'+esc(x[0])+'</p><p class=\"cap99-s\">'+esc(x[1])+'</p></div>'}).join(\"\")+'</section>'});\n  return h+'<p class=\"muted\" style=\"font-size:15px\">Sorted keeps track of what other people have promised. <a href=\"/\">Start your own</a>.</p>';\n}\nfunction viewShared(){");
R("    loadShared(token);\n",
  "    loadShared(token);try{sb.rpc(\"share_seen\",{p_token:token}).then(function(){},function(){})}catch(e){}\n");
R("If you send a helper link, that person sees that one case until you switch the link off, or until 30 days pass without a change to it.",
  "If you send a helper link, that person sees that one case until you switch the link off, or until 30 days pass without a change to it. If you share a move, they see its steps and, for each case in it, its name, who you’re waiting on, the date and the reference. Sorted counts how many times, and on how many days, a link is opened, but nothing about who opened it.");
fs.writeFileSync('public/index.html',s);
const EXPECT='88a9a3df000b336f0fcf7c0919b51731ddda1b1a';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v104 ok',h(s),s.length);
