const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='47d2186c5e24df04cf8f47315886188cfdb9a3fa')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v118 (Phase 3, part 1): Account, Settings and Help & About as three views with a selected tab; an email
// reminders switch with its state and destination; the send times on a case, UK time; usage records with their
// state; export and deletion explained; an Owner section; the sync state on Home. ----
R("var SORTED_V=\"v117\"",
  "var SORTED_V=\"v118\"");
R("  h+='<main class=\"stack fade acct112\" style=\"margin-top:8px\"><h1 class=\"h1\">Account</h1>';\n  h+='<nav class=\"acct112-nav\" aria-label=\"On this page\"><button class=\"btn quiet\" data-a=\"acct-jump\" data-v=\"acct-you\">Account</button><button class=\"btn quiet\" data-a=\"acct-jump\" data-v=\"acct-settings\">Settings</button><button class=\"btn quiet\" data-a=\"acct-jump\" data-v=\"help\">Help & About</button></nav>';\n  /* Account */\n  h+='<section class=\"stack acct112-part\" id=\"acct-you\" aria-labelledby=\"acct-you-h\"><h2 class=\"h2\" id=\"acct-you-h\">Your account</h2>';",
  "  var tab=S.view.tab||\"acct-you\",TABS=[[\"acct-you\",\"Account\"],[\"acct-settings\",\"Settings\"],[\"help\",\"Help & About\"]];\n  h+='<main class=\"stack fade acct112\" style=\"margin-top:8px\"><h1 class=\"h1\">'+esc((TABS.filter(function(x){return x[0]===tab})[0]||TABS[0])[1])+'</h1>';\n  h+='<nav class=\"acct112-nav\" role=\"tablist\" aria-label=\"Account, Settings, Help & About\">'+TABS.map(function(x){return '<button class=\"btn quiet'+(tab===x[0]?' on':'')+'\" role=\"tab\" aria-selected=\"'+(tab===x[0])+'\" aria-controls=\"'+x[0]+'\" data-a=\"acct-jump\" data-v=\"'+x[0]+'\">'+x[1]+'</button>'}).join(\"\")+'</nav>';\n  /* Account */\n  if(tab===\"acct-you\"){\n  h+='<section class=\"stack acct112-part\" id=\"acct-you\" role=\"tabpanel\" aria-labelledby=\"acct-you-h\"><h2 class=\"h2\" id=\"acct-you-h\">Your account</h2>';");
R("<p class=\"mono muted\">'+S.tasks.length+' case'+(S.tasks.length===1?\"\":\"s\")+'</p><p class=\"muted sync114\" data-sync=\"all\" role=\"status\">'+esc(syncAll())+'</p>'+(S.user&&!S.user.email?'':signoutBlock())+'</section>';",
  "<p>'+S.tasks.length+' case'+(S.tasks.length===1?\"\":\"s\")+(S.user&&S.user.email?\", linked to that email\":\", on this phone only\")+'.</p><p class=\"muted sync114\" data-sync=\"all\" role=\"status\">'+esc(syncAll())+'</p>'+(S.user&&!S.user.email?'':signoutBlock())+'</section>';");
R("  h+='<section class=\"sheet stack\"><div class=\"stack-s\"><p class=\"h3\">A copy of your data</p><p>Copy all your cases. For your usage records or anything else Sorted holds, email kofiniiakwei@gmail.com.</p></div><button class=\"btn primary block\" data-a=\"export-file\">Download all my cases as a file</button><button class=\"btn block\" data-a=\"export\">Copy all my cases (for a computer)</button><p class=\"muted\" style=\"font-size:14px;margin:0\">The file is plain text, one case after another, made on this phone. Nothing is sent anywhere.</p>';",
  "  h+='<section class=\"sheet stack\"><div class=\"stack-s\"><p class=\"h3\">A copy of your data</p><p>A plain text file (.txt), made on this phone: every case with its promises, dates, references, messages and history, then your moves. Nothing is sent anywhere. For your usage records or anything else Sorted holds, email kofiniiakwei@gmail.com.</p></div><button class=\"btn primary block\" data-a=\"export-file\">Download my cases</button><button class=\"btn block\" data-a=\"export\">Copy to clipboard</button>';");
R("  h+='<section class=\"sheet stack\"><p class=\"h3\">Delete everything</p>';\n  if(S.view.confirm)h+='<p>This deletes your account and all '+S.tasks.length+' cases, on every device. You can’t undo it.</p><div class=\"row eq\"><button class=\"btn danger\" data-a=\"wipe\">Delete everything</button><button class=\"btn\" data-a=\"wipe-cancel\">Keep it</button></div>';\n  else h+='<button class=\"btn block\" data-a=\"wipe-ask\">Delete my account and cases</button>';\n  h+='</section></section>';\n  /* Settings */\n  h+='<section class=\"stack acct112-part\" id=\"acct-settings\" aria-labelledby=\"acct-settings-h\"><h2 class=\"h2\" id=\"acct-settings-h\">Settings</h2>';\n  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Reminders</p>'+(em&&S.emailReady?'<p>When something is due, Sorted emails <strong>'+esc(em)+'</strong>. Turn emails off for one case under Reminders on that case, or for everything with the link at the bottom of any reminder email.</p>':em?'<p>Email reminders aren’t switched on for Sorted yet. Calendar reminders still work.</p>':'<p>Without an email, Sorted can only remind you when you open it. Add an email and it can email you when something is due.</p><button class=\"btn\" data-a=\"go-claim-home\">Add my email</button>')+'<p class=\"muted\" style=\"margin:0;font-size:15px\">You can also add any date to your own calendar from the case. Whatever the setting, a case that is due moves to the top of Home.</p></section>';",
  "  h+='<section class=\"sheet stack\"><p class=\"h3\">Delete my account</p>';\n  if(S.view.confirm)h+='<p>This deletes your account and your '+S.tasks.length+' case'+(S.tasks.length===1?\"\":\"s\")+' straight away, on every device: cases, helper links, unsent reminders, replies, notes, the company totals you contributed and your usage records. There is no Undo. Emails Sorted has already sent stay in your inbox.</p><div class=\"row eq\"><button class=\"btn danger\" data-a=\"wipe\">Delete my account</button><button class=\"btn\" data-a=\"wipe-cancel\">Keep it</button></div>';\n  else h+='<button class=\"btn block danger-quiet\" data-a=\"wipe-ask\">Delete my account</button><p class=\"muted\" style=\"margin:0;font-size:14px\">Everything goes at once, with no Undo. You’ll be asked to confirm.</p>';\n  h+='</section></section>';\n  }\n  /* Settings */\n  if(tab===\"acct-settings\"){\n  h+='<section class=\"stack acct112-part\" id=\"acct-settings\" role=\"tabpanel\" aria-labelledby=\"acct-settings-h\"><h2 class=\"h2\" id=\"acct-settings-h\">Settings</h2>';\n  var eo=S.emailOff===true;\n  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Email reminders</p>'+(em&&S.emailReady?'<p><strong>'+(eo?\"Off for every case.\":\"On.\")+'</strong> '+(eo?\"Sorted won’t email you about any case until you switch them back on. Cases still come to the top of Home when they’re due.\":\"When something is due, Sorted emails <strong>\"+esc(em)+\"</strong> a link, at the time shown on the case, UK time. When it arrives depends on email, and it can be late or not arrive.\")+'</p><button class=\"btn\" data-a=\"optout-toggle\" aria-pressed=\"'+(!eo)+'\">'+(eo?\"Switch email reminders on\":\"Switch email reminders off for every case\")+'</button><p class=\"muted\" style=\"margin:0;font-size:15px\">Each case has its own switch under Reminders, and every reminder email has a link that stops them all.</p>':em?'<p>Email reminders aren’t switched on for Sorted yet. Calendar reminders still work.</p>':'<p>Without an email, Sorted can only remind you when you open it. Add an email and it can email you when something is due.</p><button class=\"btn\" data-a=\"go-claim-home\">Add my email</button>')+'<p class=\"muted\" style=\"margin:0;font-size:15px\">You can also add any date to your own calendar from the case, which uses your calendar’s own alerts. Whatever the setting, a case that is due moves to the top of Home.</p></section>';");
R("  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Usage records</p><p>'+(noSteps()?\"Sorted isn’t recording which steps you use on this phone.\":\"Sorted records which steps you use, such as “promise added”, with your account id and the case id but no case content. It helps show whether Sorted works. These go when you delete your account.\")+'</p><button class=\"btn\" data-a=\"steps-toggle\">'+(noSteps()?\"Record my usage again\":\"Don’t record my usage\")+'</button></section>';\n  if(S.isAdmin)h+='<button class=\"btn block\" data-a=\"pilot\">Pilot numbers</button>';\n  h+='</section>';\n  /* Help & About */\n  h+='<section class=\"stack acct112-part\" id=\"help\" aria-labelledby=\"help-h\"><h2 class=\"h2\" id=\"help-h\">Help & About</h2>';",
  "  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Usage records</p><p><strong>'+(noSteps()?\"Off on this phone.\":\"On.\")+'</strong> '+(noSteps()?\"Sorted isn’t recording which steps you use on this phone.\":\"Sorted records which steps you use, such as “promise added”, with your account id and the case id but no case content: never what a case says. It helps show whether Sorted works. These go when you delete your account.\")+'</p><button class=\"btn\" data-a=\"steps-toggle\" aria-pressed=\"'+(!noSteps())+'\">'+(noSteps()?\"Record my usage again\":\"Don’t record my usage\")+'</button></section>';\n  if(S.isAdmin)h+='<section class=\"sheet stack-s\"><p class=\"h3\">Owner</p><p class=\"muted\" style=\"margin:0;font-size:15px\">Only the person running Sorted sees this.</p><button class=\"btn block\" data-a=\"pilot\">Pilot numbers</button></section>';\n  h+='</section>';\n  }\n  /* Help & About */\n  if(tab===\"help\"){\n  h+='<section class=\"stack acct112-part\" id=\"help\" role=\"tabpanel\" aria-labelledby=\"help-h\"><h2 class=\"h2\" id=\"help-h\">Help & About</h2>';");
R("  h+=privacyBlock();h+=termsBlock();\n  h+='</section></main>';\n  return h;\n}",
  "  h+=privacyBlock();h+=termsBlock();\n  h+='</section>';\n  }\n  h+='</main>';\n  return h;\n}");
R("    case \"acct-jump\":{var aj=$(\"#\"+b.getAttribute(\"data-v\"));if(aj){aj.scrollIntoView({block:\"start\",behavior:\"smooth\"});var ah=aj.querySelector(\"h2\");if(ah){ah.setAttribute(\"tabindex\",\"-1\");ah.focus({preventScroll:true})}}break}",
  "    case \"acct-jump\":{S.view.tab=b.getAttribute(\"data-v\")||\"acct-you\";S.view.confirm=false;render();var aj=$(\"#\"+S.view.tab);if(aj){var ah=aj.querySelector(\"h2\");if(ah){ah.setAttribute(\"tabindex\",\"-1\");ah.focus({preventScroll:true})}}window.scrollTo(0,0);break}\n    case \"optout-toggle\":{var oto=!(S.emailOff===true);sb.rpc(\"set_email_optout\",{p_off:oto}).then(function(r){if(r&&r.error){toast(\"Couldn’t change that. Check your connection.\");reportErr(\"save\",\"optout_failed\",r.error.message);return}S.emailOff=oto;toast(oto?\"Email reminders off for every case\":\"Email reminders on\");render()},function(){toast(\"Couldn’t change that. Check your connection.\")});break}");
R("    case \"help\":go({name:\"data\"});setTimeout(function(){var hp=$(\"#help\");if(hp){hp.scrollIntoView({block:\"start\"});var hh=$(\"#help-h\");if(hh){hh.setAttribute(\"tabindex\",\"-1\");hh.focus({preventScroll:true})}}},60);break;",
  "    case \"help\":go({name:\"data\",tab:\"help\"});setTimeout(function(){var hh=$(\"#help-h\");if(hh){hh.setAttribute(\"tabindex\",\"-1\");hh.focus({preventScroll:true})}},60);break;");
R("function checkEmailReady(){sb.rpc(\"email_reminders_ready\").then(function(r){var v=!!(r&&r.data===true);if(v!==!!S.emailReady){S.emailReady=v;if(S.view.name===\"task\")render()}},function(){})}",
  "function checkEmailReady(){sb.rpc(\"email_reminders_ready\").then(function(r){var v=!!(r&&r.data===true);if(v!==!!S.emailReady){S.emailReady=v;if(S.view.name===\"task\")render()}},function(){});if(S.user&&S.user.email)sb.from(\"email_optouts\").select(\"user_id\").eq(\"user_id\",S.user.id).then(function(r){var off=!!(r&&r.data&&r.data.length);if(off!==(S.emailOff===true)){S.emailOff=off;if(S.view.name===\"data\")render()}},function(){})}");
R("  if(t.emailRemind)return '<div class=\"note stack-s\"><p><strong>Email reminders are on.</strong> Sorted emails '+esc(S.user.email)+' a link at the same times. The email doesn’t say what the case is.</p><button class=\"link\" data-a=\"email-off\" style=\"align-self:flex-start\">Turn email reminders off</button></div>';",
  "  if(t.emailRemind){var et=calTimes(t).filter(function(x){return x.at>new Date()}).map(function(x){return fmtDay(x.at)+\", \"+fmtTime(x.at)});return '<div class=\"note stack-s\"><p><strong>Email reminders are on.</strong> Sorted emails '+esc(S.user.email)+' a link'+(et.length?' on '+esc(et.join(\"; \"))+' (UK time)':' at the same times')+'. When it arrives depends on email. The email doesn’t say what the case is.'+(S.emailOff===true?' <strong>You’ve switched email reminders off for every case in Settings, so none will be sent until you switch them on.</strong>':'')+'</p><button class=\"link\" data-a=\"email-off\" style=\"align-self:flex-start\">Turn email reminders off</button></div>'}");
R("    h+=foundBlock();\n    var newBtn='<button class=\"btn home111-newbtn\" data-a=\"new-case\">+ New</button>';",
  "    h+=foundBlock();\n    if(S.user&&(pendingRecs().length||isOffline()))h+='<p class=\"muted sync114 home118-sync\" data-sync=\"all\" role=\"status\">'+esc(syncAll())+'</p>';\n    var newBtn='<button class=\"btn home111-newbtn\" data-a=\"new-case\">+ New</button>';");
R("</style>\n</head>\n<body>\n<div class=\"wrap\" id=\"app\"></div>\n<d",
  "</style>\n<style>\n/* v118 */\n.acct112-nav .btn.on{background:var(--violet2,#4F39D9);border-color:transparent;color:#fff}\n.btn.danger-quiet{border-color:var(--danger,#b42318);color:var(--danger,#b42318);background:transparent}\n.home118-sync{margin:0 0 8px}\n</style>\n</head>\n<body>\n<div class=\"wrap\" id=\"app\"></div>\n<d");
fs.writeFileSync('public/index.html',s);
const EXPECT='58ca38672e33e46a7aaf763610ad9eeb8104c86f';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v118 ok',h(s),s.length);
