const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='30189ca2f049dc4b2a509fbbb19f1386d5f310c4')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+String(a).slice(0,80));s=s.split(a).join(b)}
// v82: the resolution flywheel. This layer does not change the existing promise/playbook rules.
// It adds user-controlled Autopilot, verified-rights hints, money-recovered value, adviser mode,
// parcel outcome verification, a stronger resolution-assistant entry point and answer-page seeding.
R('</style>\n\n</head>',String.raw`/* v82 resolution flywheel */
.fw-auto-status{display:flex;gap:10px;align-items:flex-start;padding:12px 14px;border:1px solid color-mix(in srgb,var(--aqua) 35%,var(--rule));border-radius:16px;background:linear-gradient(135deg,color-mix(in srgb,var(--asoft) 58%,var(--sheet)),color-mix(in srgb,var(--vsoft) 44%,var(--sheet)));font-size:15px}
.fw-auto-dot{width:10px;height:10px;border-radius:50%;margin-top:5px;flex:0 0 auto;background:var(--aqua);box-shadow:0 0 0 5px color-mix(in srgb,var(--aqua) 14%,transparent)}
.fw-auto-status.pause .fw-auto-dot{background:var(--coral);box-shadow:0 0 0 5px color-mix(in srgb,var(--coral) 14%,transparent)}
.fw-tools{display:flex;flex-direction:column;gap:14px}.fw-tool{border:1px solid color-mix(in srgb,var(--violet) 15%,var(--rule));border-radius:16px;padding:14px;background:color-mix(in srgb,var(--sheet) 97%,var(--vsoft))}.fw-tool h3,.fw-tool p{margin:0}.fw-tool .chips{margin-top:10px}.fw-sub{font-size:14px;color:var(--ink-2);margin-top:5px!important}.fw-right{border-color:color-mix(in srgb,var(--amber) 38%,var(--rule));background:linear-gradient(135deg,color-mix(in srgb,var(--amsoft) 68%,var(--sheet)),var(--sheet))}.fw-right a{font-weight:700;color:var(--carbon);text-underline-offset:3px}.fw-money-home{display:flex;align-items:center;justify-content:space-between;gap:14px;border:1px solid color-mix(in srgb,var(--green) 28%,var(--rule));border-radius:18px;padding:15px 16px;background:linear-gradient(125deg,color-mix(in srgb,var(--gsoft) 72%,var(--sheet)),color-mix(in srgb,var(--sheet) 92%,var(--asoft)))}.fw-money-home strong{font-size:24px;letter-spacing:-.02em}.fw-money-form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;margin-top:10px}.fw-money-form input{min-width:0}.fw-parcel-meta{display:grid;grid-template-columns:1fr;gap:8px;margin-top:10px}.fw-compare{margin-top:10px;padding:11px 12px;border-radius:13px;background:color-mix(in srgb,var(--amsoft) 72%,var(--sheet));font-size:15px}.fw-compare strong{display:block;margin-bottom:3px}.fw-intake-hint{margin:7px 2px 0;color:var(--ink-2);font-size:14px}.fw-value{display:inline-flex;align-items:center;gap:7px;font-weight:700;color:var(--green)}
:root[data-theme="dark"] .fw-tool{background:color-mix(in srgb,var(--sheet) 92%,var(--vsoft))}:root[data-theme="dark"] .fw-right{background:linear-gradient(135deg,color-mix(in srgb,var(--amsoft) 72%,var(--sheet)),var(--sheet))}
@media(max-width:520px){.fw-money-form{grid-template-columns:1fr}.fw-money-form .btn{width:100%}}
</style>

</head>`);
R('boot();\n})();',String.raw`/* v82 resolution flywheel */
var FW_SEEDS={
  'currys-refund':{mode:'call',title:'Currys refund not received',baseline:'Not sure yet'},
  'southwark-pcn':{mode:'call',title:'Southwark parking ticket',baseline:'Not sure yet'},
  'missed-engineer':{mode:'call',title:'Engineer did not turn up',baseline:'Not sure yet'}
};
function fwSeed(){try{return FW_SEEDS[new URLSearchParams(location.search).get('answer')]||null}catch(e){return null}}
var fwViewNew=viewNew;viewNew=function(){var z=fwSeed();if(z&&!S.draft._fwSeeded){S.draft._fwSeeded=1;S.draft.title=S.draft.title||z.title;S.draft.baseline=S.draft.baseline||z.baseline}return fwViewNew()};
function fwText(t){return [t.title||'',t.said||'',t.outcome||'',(t.facts&&t.facts.party)||'',(t.fix&&t.fix.party)||'',(t.fix&&t.fix.seller)||''].concat((t.promises||[]).map(function(p){return [p.party,p.said,p.status].join(' ')})).concat((t.events||[]).slice(-20).map(function(e){return e.label||''})).join(' ')}
function fwMode(t){return t.autoMode||'assist'}
function fwAutoStatus(t){if(!t||t.board==='done')return '';var m=fwMode(t),st=state(t),need=st==='yours'||st==='due';if(m==='remember')return '';var tx=need?'Autopilot has paused because this needs your decision.':m==='run'?'Sorted is holding this case. It will surface a reply, a missed promise or a decision when it matters.':'Sorted is watching the dates and replies in this case and will prepare the next move when it can.';return '<div class="fw-auto-status'+(need?' pause':'')+'"><span class="fw-auto-dot" aria-hidden="true"></span><span><strong>'+(m==='run'?'Autopilot on':'Sorted is watching')+'.</strong> '+esc(tx)+'</span></div>'}
function fwAutoTool(t){var m=fwMode(t),copy=m==='run'?'Safe administration can happen automatically. Sorted still asks before sending, submitting, paying, accepting, admitting or closing anything.':m==='assist'?'Sorted watches what changes and prepares the next step. You approve consequential actions.':'Sorted keeps the record, promises and dates, but leaves the next action to you.';return '<section class="fw-tool"><h3 class="h3">Case Autopilot</h3><p class="fw-sub">Give Sorted the problem once. Choose how much help you want on this case.</p><div class="chips" role="group" aria-label="Autopilot level">'+[['remember','Remember'],['assist','Assist'],['run','Run the admin']].map(function(x){return '<button type="button" class="chip" data-fw="auto" data-v="'+x[0]+'" aria-pressed="'+(m===x[0])+'">'+x[1]+'</button>'}).join('')+'</div><p class="fw-sub">'+esc(copy)+'</p></section>'}
var FW_TEL=[/\bBT\b/i,/\bEE\b/i,/\bHyperoptic\b/i,/\bPlusnet\b/i,/\bSky\b/i,/\bNOW Broadband\b/i,/\bTalkTalk\b/i,/\bUtility Warehouse\b/i,/\bVirgin Media\b/i,/\bVodafone\b/i,/\bZen\b/i];
function fwRight(t){var x=fwText(t),miss=(t.promises||[]).some(function(p){return p.status==='missed'&&/engineer|appointment|visit|technician|repair/i.test(p.said||'')});
  if(miss&&FW_TEL.some(function(r){return r.test(x)})&&/broadband|landline|internet|engineer|phone/i.test(x))return {k:'telecom',title:'There may be automatic compensation here',body:'For a qualifying residential fixed broadband or landline case under Ofcom’s Automatic Compensation Scheme, the current rate for a missed engineer appointment is £32.31. The scheme has eligibility rules, so check the official page before relying on it.',url:'https://www.ofcom.org.uk/phones-and-broadband/service-quality/automatic-compensation-need-know',link:'Check Ofcom’s rules'};
  if(/\b(train|rail|railway|delay repay)\b/i.test(x)&&/delay|late|cancel/i.test(x))return {k:'rail',title:'You may be able to claim for the journey',body:'National Rail says delayed or cancelled journeys may qualify for a refund or compensation, including Delay Repay. The amount and threshold depend on the train company, ticket and delay.',url:'https://www.nationalrail.co.uk/help-and-assistance/compensation-and-refunds/',link:'Check National Rail'};
  if(/\b(flight|airline|airport|easyjet|ryanair|british airways|BA|wizz|jet2)\b/i.test(x)&&/delay|late|cancel/i.test(x))return {k:'flight',title:'Passenger-rights compensation may apply',body:'CAA guidance says UK261 can provide care, refunds or fixed compensation in some delayed or cancelled flight cases. Eligibility depends on the route, delay, notice and cause, so Sorted will not assume you are entitled.',url:'https://www.caa.co.uk/air-passengers/travel-problems-and-rights/flight-delays-and-cancellations/delays/',link:'Check CAA passenger rights'};
  return null}
function fwRightsTool(t){var r=fwRight(t);if(!r)return '';return '<section class="fw-tool fw-right"><h3 class="h3">What you may be owed</h3><p><strong>'+esc(r.title)+'</strong></p><p class="fw-sub">'+esc(r.body)+'</p><p class="fw-sub"><a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">'+esc(r.link)+' ↗</a> · Official source checked 2 Oct 2026.</p></section>'}
function fwMoney(t){return t&&t.money&&Number(t.money.recovered)>0?Number(t.money.recovered):0}
function fwMoneyTotal(){return (S.tasks||[]).filter(function(t){return !t.example}).reduce(function(a,t){return a+fwMoney(t)},0)}
function fwMoneyTool(t){var n=fwMoney(t);return '<section class="fw-tool"><h3 class="h3">Money recovered</h3>'+(n?'<p class="fw-value">£'+n.toFixed(2).replace(/\.00$/,'')+' recorded for this case</p><p class="fw-sub">Only count money or credit you have actually received.</p>':'<p class="fw-sub">When a refund, compensation payment or bill credit actually lands, record it here. This lets Sorted show the value it helped you recover.</p>')+'<form class="fw-money-form" data-fw-form="money"><label class="f"><span class="sr-only">Amount recovered</span><input inputmode="decimal" name="amount" placeholder="Amount actually received" value="'+(n?n.toFixed(2):'')+'"></label><button class="btn" type="submit">'+(n?'Update':'Record')+'</button></form></section>'}
function fwMoneyHome(){var n=fwMoneyTotal();if(!n)return '';return '<section class="fw-money-home"><div><p class="eyebrow" style="margin:0">Sorted value</p><p style="margin:2px 0 0">Money you recorded as recovered</p></div><strong>£'+n.toFixed(2).replace(/\.00$/,'')+'</strong></section>'}
var FW_CARRIERS={royalmail:['Royal Mail','https://www.royalmail.com/track-your-item'],dpd:['DPD','https://track.dpd.co.uk/'],evri:['Evri','https://www.evri.com/track-a-parcel'],dhl:['DHL','https://www.dhl.com/gb-en/home/tracking.html'],ups:['UPS','https://www.ups.com/track'],fedex:['FedEx','https://www.fedex.com/en-gb/tracking.html']};
function fwParcelRelevant(t){return !!(t.verify&&t.verify.kind==='parcel')||/\b(parcel|package|delivery|courier|tracking|royal mail|dpd|evri|dhl|ups|fedex)\b/i.test(fwText(t))}
function fwParcelTool(t){if(!fwParcelRelevant(t))return '';var v=t.verify&&t.verify.kind==='parcel'?t.verify:{carrier:'',tracking:'',status:''},c=FW_CARRIERS[v.carrier];var h='<section class="fw-tool"><h3 class="h3">Verify the delivery</h3><p class="fw-sub">Keep the tracking reference with the case. Sorted can send you to the carrier’s official tracker, then you confirm what happened. A live carrier adapter can replace this check later without changing the case.</p><form class="fw-parcel-meta" data-fw-form="parcel"><label class="f">Carrier<select name="carrier"><option value="">Choose carrier</option>'+Object.keys(FW_CARRIERS).map(function(k){return '<option value="'+k+'"'+(v.carrier===k?' selected':'')+'>'+FW_CARRIERS[k][0]+'</option>'}).join('')+'</select></label><label class="f">Tracking reference<input name="tracking" autocomplete="off" value="'+esc(v.tracking||'')+'"></label><button class="btn" type="submit">Save tracking</button></form>';if(c&&v.tracking)h+='<p class="fw-sub"><a href="'+esc(c[1])+'" target="_blank" rel="noopener noreferrer">Open '+esc(c[0])+' official tracking ↗</a></p><button class="btn block" type="button" data-fw="parcel-delivered">I checked. It was delivered</button>';if(v.status==='delivered')h+='<p class="fw-value">✓ Delivery confirmed by you</p>';return h+'</section>'}
function fwResolutionTool(t){if(t.example)return '';return '<section class="fw-tool"><h3 class="h3">Resolution Assistant</h3><p class="fw-sub">Use the whole confirmed case, not a blank chatbot. Sorted can explain what changed, point out missing information and prepare a factual follow-up.</p><button type="button" class="btn block" data-fw="resolve">Help me resolve this</button></section>'}
function fwAdviserLabel(){Array.from(document.querySelectorAll('button.link')).forEach(function(b){if(/Prepare this for an adviser/i.test(b.textContent||''))b.textContent='Adviser mode · prepare a one-page case pack'})}
function fwToolsHTML(t){return '<div class="fw-tools">'+fwAutoTool(t)+fwRightsTool(t)+fwMoneyTool(t)+fwResolutionTool(t)+fwParcelTool(t)+'</div>'}
function fwReplyCompare(t){var cm=document.querySelector('.cm-card');if(!cm||cm.querySelector('.fw-compare'))return;var p=openPromise(t);if(!p)return;var x=document.createElement('div');x.className='fw-compare';x.innerHTML='<strong>Compared with what Sorted was holding</strong>'+esc((p.party||'They')+' said: '+p.said)+'<br><span class="mono">'+esc(whenText(p))+(p.ref?' · Ref '+esc(p.ref):'')+'</span>';var body=cm.querySelector('.cm-body');if(body)body.insertAdjacentElement('afterend',x);else cm.appendChild(x)}
function fwEnhance(){try{
  if(S.view.name==='home'){
    var nb=document.querySelector('.home44-new');if(nb){nb.textContent='＋ Add anything';if(!nb.nextElementSibling||!nb.nextElementSibling.classList.contains('fw-intake-hint'))nb.insertAdjacentHTML('afterend','<p class="fw-intake-hint">Photo, PDF, screenshot, message or letter. Sorted will work out what belongs in the case, then ask you to confirm it.</p>')}
    var main=document.querySelector('main');if(main&&!document.querySelector('.fw-money-home')){var html=fwMoneyHome();if(html){var came=document.querySelector('.found-strip');if(came)came.insertAdjacentHTML('afterend',html);else main.insertAdjacentHTML('afterbegin',html)}}
  }
  if(S.view.name==='task'){
    var t=task(S.view.id);if(!t)return;var title=document.querySelector('.case56-title');if(title&&!document.querySelector('.fw-auto-status'))title.closest('section').insertAdjacentHTML('afterend',fwAutoStatus(t));
    var body=document.querySelector('.case75-tools .case75-group-body');if(body&&!body.querySelector('.fw-tools'))body.insertAdjacentHTML('afterbegin',fwToolsHTML(t));
    fwReplyCompare(t);fwAdviserLabel();
  }
}catch(e){}}
var fwRender=render;render=function(){var r=fwRender();fwEnhance();return r};
document.addEventListener('click',function(e){var b=e.target.closest('[data-fw]');if(!b)return;var t=S.view.id?task(S.view.id):null,a=b.getAttribute('data-fw');if(!t)return;
  if(a==='auto'){var v=b.getAttribute('data-v');if(!/^(remember|assist|run)$/.test(v))return;t.autoMode=v;log(t,'Autopilot set to '+v+'.');t._dirty=true;commit();return}
  if(a==='resolve'){S.view.panel='aiask';S.draft={aiq:'What has changed in this case, what information or evidence may be missing, and what safe options can I consider next? If a factual follow-up would help, draft one using only the confirmed facts in this case.'};render();window.scrollTo(0,0);return}
  if(a==='parcel-delivered'){t.verify=t.verify||{kind:'parcel'};t.verify.status='delivered';t.verify.checkedAt=nowIso();log(t,'You checked the carrier tracking and confirmed the parcel was delivered.');t._dirty=true;commit();return}
});
document.addEventListener('submit',function(e){var f=e.target.closest('[data-fw-form]');if(!f)return;e.preventDefault();var t=S.view.id?task(S.view.id):null;if(!t)return;var k=f.getAttribute('data-fw-form');
  if(k==='money'){var n=parseFloat(String(new FormData(f).get('amount')||'').replace(/[^0-9.]/g,''));if(!isFinite(n)||n<0||n>100000){toast('Add the amount actually received.');return}t.money=t.money||{};t.money.recovered=Math.round(n*100)/100;t.money.at=nowIso();log(t,'Recorded £'+t.money.recovered.toFixed(2)+' actually recovered.');t._dirty=true;commit();toast('Recorded');return}
  if(k==='parcel'){var fd=new FormData(f),car=String(fd.get('carrier')||''),tr=String(fd.get('tracking')||'').trim().slice(0,80);if(!FW_CARRIERS[car]||!tr){toast('Choose the carrier and add the tracking reference.');return}t.verify={kind:'parcel',carrier:car,tracking:tr,status:(t.verify&&t.verify.status)||'',savedAt:nowIso()};log(t,'Saved '+FW_CARRIERS[car][0]+' tracking reference.');t._dirty=true;commit();toast('Tracking saved');return}
},true);
boot();
})();`);
fs.writeFileSync('public/index.html',s);
const EXPECT='0000000000000000000000000000000000000000';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v82 ok',h(s),s.length);
