const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='1b0d3d37bf17480842cd087b2fb9e4bba0bc9c57')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v123: "Whose move is it now?" (Mine, Theirs, Both) can be asked again at any time; an answer that conflicts with
// an open step of yours asks whether to keep the step or mark it no longer needed, never silently; the landing page
// leads with the headline, one explanation, the kinds of matter and one primary button. ----
R("function turnBlock(t){\n  var who=turnWho(t)||\"them\";\n  return '<div class=\"stack-s turn117\" role=\"group\" aria-labelledby=\"turnh\"><p class=\"h3\" id=\"turnh\" style=\"margin:0\">Whose move is it?</p><p class=\"muted\" style=\"margin:0;font-size:15px\">Are you waiting for '+esc(who)+', or have they asked you for something?</p><div class=\"chips\"><button class=\"chip\" data-a=\"turn-theirs\">I’m waiting for '+esc(who)+'</button><button class=\"chip\" data-a=\"turn-yours\">They’ve asked me for something</button><button class=\"chip\" data-a=\"turn-both\">Both</button></div></div>';\n}",
  "/* v123: the question is \"Whose move is it now?\" with Mine, Theirs and Both. It can be asked again at any time from What\n   Sorted understood. Responsibility lives on the obligations themselves (their promise, your step); the answer is what\n   the person said, kept beside them. An answer that conflicts with an open step of yours is never applied silently:\n   Sorted asks whether to keep the step as well or mark it no longer needed. */\nfunction turnBlock(t){\n  var who=turnWho(t)||\"them\",cur=t.turn||\"\",m=openMove(t),p=openPromise(t),c=S.view.turnConf;\n  if(c){\n    var mw=m?m.what.replace(/[.!]+$/,\"\"):\"\";\n    return '<div class=\"stack-s turn117 turn123-conf\" role=\"group\" aria-labelledby=\"turnh\"><p class=\"h3\" id=\"turnh\" style=\"margin:0\">You have a step open: “'+esc(mw)+'”'+(m&&m.dueAt?\", \"+esc(whenText(m).replace(/^By/,\"by\")):\"\")+'.</p><p class=\"muted\" style=\"margin:0;font-size:15px\">You said it’s '+esc(who)+'’s move now. Nothing has changed yet. What should happen to your step?</p><div class=\"chips\"><button class=\"chip\" data-a=\"turn-keep\">Keep my step as well</button><button class=\"chip\" data-a=\"turn-dropstep\">Mark my step no longer needed</button><button class=\"chip\" data-a=\"turn-leave\">Leave it as it was</button></div></div>';\n  }\n  var hint=p&&m?\"Their promise and your step are both on the case.\":p?(p.party||who)+\" said they would, and the date is on the case.\":m?\"Your step “\"+m.what.replace(/[.!]+$/,\"\")+\"” is open.\":\"Are you waiting for \"+who+\", or have they asked you for something?\";\n  var ch=function(a,v,l){return '<button class=\"chip\" data-a=\"'+a+'\" aria-pressed=\"'+(cur===v)+'\">'+l+'</button>'};\n  return '<div class=\"stack-s turn117\" role=\"group\" aria-labelledby=\"turnh\"><p class=\"h3\" id=\"turnh\" style=\"margin:0\">Whose move is it now?</p><p class=\"muted\" style=\"margin:0;font-size:15px\">'+esc(hint)+'</p><div class=\"chips\">'+ch(\"turn-yours\",\"yours\",\"Mine: \"+esc(who)+\" asked me for something\")+ch(\"turn-theirs\",\"theirs\",\"Theirs: I’m waiting for \"+esc(who))+ch(\"turn-both\",\"both\",\"Both\")+'</div>'+(S.view.turnAsk?'<button class=\"btn quiet\" data-a=\"turn-leave\" style=\"align-self:flex-start\">Leave it as it is</button>':'')+'</div>';\n}\nfunction turnApply(t,v){\n  var who=turnWho(t)||\"them\",m=openMove(t),p=openPromise(t);\n  t.turn=v;t.turnAt=nowIso();S.view.turnAsk=false;S.view.turnConf=null;\n  log(t,\"Whose move: \"+(v===\"theirs\"?\"theirs. You’re waiting for \"+who+\".\":v===\"both\"?\"both. \"+(turnWho(t)||\"They\")+\" asked you for something, and you’re waiting on them too.\":\"yours. \"+(turnWho(t)||\"They\")+\" asked you for something.\")+(v===\"theirs\"&&m?\" Your step stays open.\":\"\")+(v!==\"theirs\"&&p?\" Their promise stays on the case.\":\"\"));\n  track(\"turn_recorded\",t,{turn:v});t._dirty=true;\n}");
R("function turnText(t){var who=turnWho(t)||\"them\";if(t.turn===\"theirs\")return \"Theirs: you’re waiting for \"+who+\".\";if(t.turn===\"yours\")return \"Yours: \"+who+\" asked you for something.\";if(t.turn===\"both\")return \"Both: \"+who+\" asked you for something, and you’re waiting on them too.\";var p=openPromise(t),m=openMove(t);",
  "function turnText(t){var who=turnWho(t)||\"them\",p=openPromise(t),m=openMove(t);if(t.turn===\"theirs\")return \"Theirs: you’re waiting for \"+who+\".\"+(m?\" Your step “\"+m.what.replace(/[.!]+$/,\"\")+\"” is open too.\":\"\");if(t.turn===\"yours\")return \"Yours: \"+who+\" asked you for something.\"+(p?\" Their promise is on the case too.\":\"\");if(t.turn===\"both\")return \"Both: \"+who+\" asked you for something, and you’re waiting on them too.\";");
R("case \"turn-theirs\":if(t){t.turn=\"theirs\";t.turnAt=nowIso();log(t,\"Whose move: theirs. You’re waiting for \"+(turnWho(t)||\"them\")+\".\");track(\"turn_recorded\",t,{turn:\"theirs\"});commit()}break;\n    case \"turn-yours\":case \"turn-both\":if(t){t.turn=a===\"turn-both\"?\"both\":\"yours\";t.turnAt=nowIso();log(t,\"Whose move: \"+(t.turn===\"both\"?\"both. \"+(turnWho(t)||\"They\")+\" asked you for something, and you’re waiting on them too.\":\"yours. \"+(turnWho(t)||\"They\")+\" asked you for something.\"));track(\"turn_recorded\",t,{turn:t.turn});t._dirty=true;S.view.panel=\"move\";S.draft={mwhat:\"\",when:\"by\",asked:true,mhint:\"What have \"+(turnWho(t)||\"they\")+\" asked you for, and by when?\"};render();var mfy=$(\"#moveform\");if(mfy)mfy.scrollIntoView({block:\"start\"})}break;\n    case \"turn-reset\":if(t){delete t.turn;t._dirty=true;S.view.uOpen=true;commit()}break;",
  "case \"turn-theirs\":if(t){if(openMove(t)){S.view.turnConf={turn:\"theirs\"};S.view.uOpen=true;render();var tcf=document.querySelector(\".turn123-conf .chip\");if(tcf)tcf.focus();break}turnApply(t,\"theirs\");commit()}break;\n    case \"turn-keep\":if(t){turnApply(t,\"theirs\");commit();toast(\"Kept your step\")}break;\n    case \"turn-dropstep\":if(t){var tdm=openMove(t);if(tdm){tdm.status=\"dropped\";tdm.closedAt=nowIso();log(t,\"Your step no longer needed: \"+tdm.what.replace(/[.!]+$/,\"\")+\".\")}turnApply(t,\"theirs\");commit();toast(\"Step marked no longer needed\")}break;\n    case \"turn-leave\":if(t){S.view.turnConf=null;S.view.turnAsk=false;S.view.uOpen=true;render()}break;\n    case \"turn-yours\":case \"turn-both\":if(t){var tv=a===\"turn-both\"?\"both\":\"yours\",hadMove=!!openMove(t);turnApply(t,tv);if(hadMove){commit();break}S.view.panel=\"move\";S.draft={mwhat:\"\",when:\"by\",asked:true,mhint:\"What have \"+(turnWho(t)||\"they\")+\" asked you for, and by when?\"};save();render();var mfy=$(\"#moveform\");if(mfy)mfy.scrollIntoView({block:\"start\"})}break;\n    case \"turn-reset\":if(t){S.view.turnAsk=true;S.view.turnConf=null;S.view.uOpen=true;render();var trh=document.getElementById(\"turnh\");if(trh)trh.scrollIntoView({block:\"center\"})}break;");
R("  if(turnAsk(t))qs+=turnBlock(t);\n  var open=!!qs||S.view.uO",
  "  if(turnAsk(t)||S.view.turnAsk||S.view.turnConf)qs+=turnBlock(t);\n  var open=!!qs||S.view.uO");
R("'+(t.turn?'<button class=\"btn quiet\" data-a=\"turn-reset\">Change whose move</button>':'')+'</div>':(t.turn?'<button class=\"btn quiet\" data-a=\"turn-reset\" style=\"align-self:flex-start\">Change whose move</button>':''))+",
  "'+(t.mode===\"call\"&&!pkOn(t)&&!S.view.turnAsk&&!S.view.turnConf?'<button class=\"btn quiet\" data-a=\"turn-reset\">'+(t.turn?\"Change whose move\":\"Say whose move it is\")+'</button>':'')+'</div>':(t.mode===\"call\"&&!pkOn(t)&&!S.view.turnAsk&&!S.view.turnConf?'<button class=\"btn quiet\" data-a=\"turn-reset\" style=\"align-self:flex-start\">'+(t.turn?\"Change whose move\":\"Say whose move it is\")+'</button>':''))+");
R(".turn117 .chips .chip{min-height:44px}\n",
  ".turn117 .chips .chip{min-height:44px}\n.turn117 .chip[aria-pressed=true]{background:var(--violet2,#4F39D9);border-color:transparent;color:#fff}\n");
R("<h1 class=\"h1\">They said Tuesday.<br><em>Sorted remembers Tuesday.</em></h1><p class=\"lede\">A parking notice. A refund that hasn’t arrived. A landlord repair. A letter you’re not sure about. Keep the details, messages, references, deadlines and next steps together, and see what needs you, what you’re waiting for and where to pick things up again. You don’t have to keep remembering whether they got back to you.</p><p class=\"pilot-line\">A small UK service, run by one person. You can start without an account. Your cases are stored in London and stay private. Idle cases are deleted after 90 days, and without an email after 30 days in which you don’t open Sorted. <a class=\"link\" href=\"#how\">See how it works</a>.</p>'+('<a class=\"btn primary\" href=\"#start\" style=\"align-self:flex-start\">Get something sorted →</a>'+'<img class=\"hero-art\" src=\"/art/hero-case.webp\" width=\"640\" height=\"410\" alt=\"A case folder with a washing machine, a clock and a phone\" fetchpriority=\"high\">')+'</section>'+landingExamples();",
  "<h1 class=\"h1\">They said Tuesday.<br><em>Sorted remembers Tuesday.</em></h1><p class=\"lede\">Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Sorted shows what needs you, what you’re waiting for and when to follow up.</p><p class=\"hero-kinds\">Refunds · repairs · parking notices · claims · important calls · moving home</p>'+('<a class=\"btn primary hero-cta\" href=\"#start\" style=\"align-self:flex-start\">Get something sorted →</a>'+'<img class=\"hero-art\" src=\"/art/hero-case.webp\" width=\"640\" height=\"410\" alt=\"A case folder with a washing machine, a clock and a phone\" fetchpriority=\"high\">'+'<p class=\"hero-note\">You don’t have to keep remembering whether they got back to you. Run by one person in the UK; start without an account. <a class=\"link\" href=\"#how\">See how it works</a>.</p>')+'</section>'+landingExamples();");
R(".cap85-public .hero .cap85-top-cta{display:none!important}",
  ".cap85-public .hero .cap85-top-cta{display:inline-flex;align-self:flex-start;margin-top:4px}\n.hero-kinds{margin:0;font-size:15px;color:var(--ink-2);letter-spacing:.01em}\n.hero-note{margin:0;font-size:14px;line-height:1.4;color:var(--ink-2)}\n.hero-note .link{display:inline;min-height:0;padding:0;font-size:inherit}");
R(".cap85-public .hero .hero-art{display:block;width:min(70%,270px);height:auto;max-width:270px;margin:3px auto -2px;filter:drop-shadow(0 14px 22px rgba(28,42,110,.2))}",
  ".cap85-public .hero .hero-art{display:block;width:min(48%,180px);height:auto;max-width:180px;margin:0 auto -2px;filter:drop-shadow(0 14px 22px rgba(28,42,110,.2))}");
R(".cap85-public .hero .h1{font-size:clamp(34px,9.8vw,46px);line-height:.98;max-width:12.5ch;",
  ".cap85-public .hero .h1{font-size:clamp(28px,8.4vw,40px);line-height:1.02;max-width:18ch;");
R("@media(max-width:520px){.cap85-public .hero{padding:17px 16px 14px}.cap85-public .hero .h1{font-size:clamp(34px,10.2vw,43px);max-width:11.7ch}.cap85-public .hero .lede{font-size:16px}.cap85-public .hero .hero-art{width:220px;max-width:62%;margin-top:0}",
  "@media(max-width:520px){.cap85-public .hero{padding:17px 16px 14px}.cap85-public .hero .h1{font-size:clamp(28px,8.4vw,34px);max-width:18ch}.cap85-public .hero .lede{font-size:16px}.cap85-public .hero .hero-art{width:170px;max-width:48%;margin-top:0}");
R("content=\"They said Tuesday. Sorted remembers Tuesday. One calm place to work out what to do, keep track of what people promise, and come back when it matters.\"",
  "content=\"They said Tuesday. Sorted remembers Tuesday. Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Sorted shows what needs you, what you’re waiting for and when to follow up.\"");
R("Keep the details, messages, references, deadlines and next steps together. Choose what’s happening and Sorted works out the next move.",
  "Keep the details, promises, deadlines and next steps of life’s unfinished business in one place. Choose what’s happening and Sorted works out the next move.");
fs.writeFileSync('public/index.html',s);
const EXPECT='c41e1c1c9caf74b0471dbe46f997658109dca348';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v123 ok',h(s),s.length);
