const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='30189ca2f049dc4b2a509fbbb19f1386d5f310c4')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v82: "What Sorted can help with" tiles on Home and in the start box; the spotlight shows your own step and lets you
// tick it off; an existing renewal step points to GOV.UK; a reference must contain a digit; complaints are named. ----
R("function caseEntry(){",
  "/* v82: \"What Sorted can help with\". Tiles on Home teach what Sorted is for; each one opens the start box with an example\n   to follow. Large while someone has few cases, a small row after that. Nothing is created until they press Start. */\nvar TILES=[\n [\"refund\",\"Refund not arrived\",\"Money they said they’d send\",\"Currys said my refund would arrive by Friday, order 445566\"],\n [\"repair\",\"Engineer or repair\",\"A visit, a repair or a no-show\",\"British Gas said the engineer will come on Tuesday between 8 and 12\"],\n [\"delivery\",\"Delivery\",\"A parcel or a replacement\",\"Amazon said my parcel will arrive tomorrow\"],\n [\"parking\",\"Parking ticket\",\"Pay or challenge, dates worked out\",\"Add a photo of the ticket below, or type what it says\"],\n [\"housing\",\"Landlord or housing\",\"Repairs, deposits, replies\",\"My landlord said they’d fix the heating by Friday\"],\n [\"complaint\",\"No reply to a complaint\",\"Chase it, then the next step\",\"I complained to Thames Water on 1 October and they haven’t replied\"]];\nfunction tileOf(k){for(var i=0;i<TILES.length;i++)if(TILES[i][0]===k)return TILES[i];return null}\nfunction tilesBlock(big){\n  if(big)return '<section class=\"tiles-full stack-s\" aria-labelledby=\"tiles-h\"><p class=\"eyebrow\">What Sorted can help with</p><h2 class=\"h3\" id=\"tiles-h\">Pick one to start, or just tell Sorted in your own words.</h2><div class=\"tiles-grid\">'+TILES.map(function(x){return '<button class=\"tile\" data-a=\"tile\" data-v=\"'+x[0]+'\"><span class=\"tile-name\">'+esc(x[1])+'</span><span class=\"tile-sub\">'+esc(x[2])+'</span></button>'}).join(\"\")+'</div>'+(S.tasks.some(function(x){return x.example})?'':'<button class=\"link\" data-a=\"example\" style=\"align-self:flex-start\">Or see a finished example first</button>')+'</section>';\n  return '<section class=\"tiles-row\" aria-label=\"Start from an example\"><p class=\"muted\" style=\"font-size:14px;margin:0\">Or start from:</p><div class=\"tiles-chips\">'+TILES.map(function(x){return '<button class=\"chip\" data-a=\"tile\" data-v=\"'+x[0]+'\">'+esc(x[1])+'</button>'}).join(\"\")+'</div></section>';\n}\n/* the official place to do a renewal, from the same hand-checked table renewals always used */\nfunction doOfficial(t){\n  if(t.mode!==\"do\")return \"\";var x=(t.title||\"\")+\" \"+(t.said||\"\"),k=/passport/i.test(x)?\"passport\":/tv licen/i.test(x)?\"tv\":/licen[cs]e/i.test(x)?\"licence\":/\\bmot\\b/i.test(x)?\"mot\":/(car|road|vehicle) tax/i.test(x)?\"tax\":\"\";\n  var o=k&&OFFICIAL[k];if(!o||!o.url)return \"\";\n  return '<p class=\"note\" style=\"margin:0\">Do it on the official site: <a href=\"'+esc(o.url)+'\" target=\"_blank\" rel=\"noopener\">'+esc(o.url.replace(/^https:\\/\\/(www\\.)?/,\"\").replace(/\\/.*$/,\"\"))+'</a>. Sorted can’t renew it for you, but it can remind you.</p>';\n}\nfunction caseEntry(){");
R("(S.tasks.length?'<h2 class=\"h2\">What do you need to sort out?</h2>':'<h1 class=\"h1\">What do you need to sort out?</h1>')",
  "(function(){var tl=d.tile&&tileOf(d.tile),hd=tl?tl[1]:\"What do you need to sort out?\";return (S.tasks.length?'<h2 class=\"h2\">'+esc(hd)+'</h2>':'<h1 class=\"h1\">'+esc(hd)+'</h1>')+(tl?'<p class=\"muted\" style=\"margin:0\">'+(d.tile===\"parking\"?'Add a photo of the ticket below, or type what it says.':'Say who said what, and when. For example: “'+esc(tl[3])+'”')+' <button class=\"link\" data-a=\"tile\" data-v=\"\" style=\"display:inline;min-height:0;padding:0\">Something else</button></p>':'')})()");
R("placeholder=\"Washing machine stopped draining\">",
  "placeholder=\"'+esc(d.tile&&tileOf(d.tile)?(d.tile===\"parking\"?\"PCN number, amount, date\":\"Type it in your own words\"):\"Washing machine stopped draining\")+'\">");
R("'<p class=\"muted\" style=\"font-size:15px\">For example “Landlord still hasn’t fixed the heating” or “Refund from Currys hasn’t arrived”.</p>'",
  "(d.tile?'':(S.tasks.length?tilesBlock(false):'<p class=\"muted\" style=\"font-size:15px\">For example “Landlord still hasn’t fixed the heating” or “Refund from Currys hasn’t arrived”.</p>'))");
R("  if(entryFirst&&!S.tasks.some(function(x){return x.example}))h+='<p class=\"muted\" style=\"font-size:16px\">Not ready yet? <button class=\"link\" data-a=\"example\" style=\"display:inline-block;padding:10px 0\">See how it works with an example case</button></p>';",
  "  if(entryFirst&&!S.draft.tile)h+=tilesBlock(true);");
R("      h+='<div class=\"home44-compose\">'+(S.composeOpen?caseEntry():'<button class=\"btn block home44-new\" data-a=\"compose\">+ Sort something new</button>')+'</div>';",
  "      h+='<div class=\"home44-compose\">'+(S.composeOpen?caseEntry():'<button class=\"btn block home44-new\" data-a=\"compose\">+ Sort something new</button>'+(S.tasks.filter(function(x){return !x.example}).length<=2?tilesBlock(true):tilesBlock(false)))+'</div>';");
R("    case \"compose\":S.composeOpen=true;render();var cf=$(\"#f-case\");if(cf)cf.focus();break;",
  "    case \"compose\":S.composeOpen=true;render();var cf=$(\"#f-case\");if(cf)cf.focus();break;\n    case \"tile\":{var tv=b.getAttribute(\"data-v\")||\"\",keep=S.draft&&S.draft.casetext;S.composeOpen=true;S.draft={tile:tv||null};if(keep)S.draft.casetext=keep;if(S.view.name!==\"home\")S.view={name:\"home\"};render();var tcf=$(\"#f-case\");if(tcf){tcf.focus();tcf.scrollIntoView({block:\"center\"})}break}\n    case \"home-move\":{var hmid=b.getAttribute(\"data-id\");S.retSrc=\"home\";go({name:\"task\",id:hmid,panel:null});var hmb=document.querySelector('[data-a=\"move-done\"]');if(hmb)hmb.click();break}");
R("    var next=m?moveTitle(m):nextStepText(t),meta=home44Meta(t);\n    h+='<p class=\"home44-question\">'+esc(next)+'</p>'+(meta&&meta!==next?'<p class=\"home44-meta\">'+esc(meta)+'</p>':'');\n    h+='<button class=\"btn primary home44-open\" data-a=\"open\" data-id=\"'+t.id+'\">Open this case</button>';",
  "    if(m&&m.what){\n      h+='<p class=\"home44-question\">'+esc(cap1(String(m.what).replace(/[.!]+$/,\"\")))+'</p><p class=\"home44-meta\">'+esc(m.dueAt?(moveTitle(m)===\"Your move\"?\"\":moveTitle(m)+\" · \")+whenText(m):\"No date set\")+'</p>';\n      h+='<div class=\"home44-actions\"><button class=\"btn primary\" data-a=\"home-move\" data-id=\"'+t.id+'\">'+esc(moveAct(m.what).done)+'</button><button class=\"btn\" data-a=\"open\" data-id=\"'+t.id+'\">Open this case</button></div>';\n    }else{\n    var next=m?moveTitle(m):nextStepText(t),meta=home44Meta(t);\n    h+='<p class=\"home44-question\">'+esc(next)+'</p>'+(meta&&meta!==next?'<p class=\"home44-meta\">'+esc(meta)+'</p>':'');\n    h+='<button class=\"btn primary home44-open\" data-a=\"open\" data-id=\"'+t.id+'\">Open this case</button>';}");
R("  if(t.mode===\"do\")return \"What’s the next step?\";",
  "  if(t.mode===\"do\")return \"Add your next step and when\";");
R("  if(mv&&s!==\"done\"&&!(mv.src===\"parking\"&&pkOn(t)))h+=moveCard(t,mv);",
  "  if(mv&&s!==\"done\"&&!(mv.src===\"parking\"&&pkOn(t)))h+=moveCard(t,mv)+doOfficial(t);");
R("  var m=/^(.*?)[\\s]*[·•]\\s*([A-Z0-9][A-Z0-9-]{3,})$/i.exec(x),ref=\"\";",
  "  var m=/^(.*?)[\\s]*[·•]\\s*((?=[A-Z-]*\\d)[A-Z0-9][A-Z0-9-]{3,})$/i.exec(x),ref=\"\";");
R("[/\\bcomplaint\\b/i,\"complaint\"]",
  "[/\\bcomplain(?:t|ts|ed|ing)?\\b/i,\"complaint\"]");
R(".pk-card p{margin:0}",
  ".pk-card p{margin:0}\n.tiles-full{margin-top:8px}\n.tiles-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}\n.tile{display:flex;flex-direction:column;align-items:flex-start;gap:3px;text-align:left;min-height:84px;padding:13px 13px;border-radius:16px;border:1px solid color-mix(in srgb,var(--violet,#6D4CFF) 22%,var(--rule));background:linear-gradient(145deg,var(--sheet),color-mix(in srgb,var(--sheet) 88%,var(--vsoft,#EEE9FF)));color:var(--ink);font:inherit;cursor:pointer;box-shadow:0 6px 18px rgba(31,27,65,.05)}\n.tile:hover{border-color:var(--violet,#6D4CFF)}\n.tile-name{font-weight:700;font-size:16px;line-height:1.2}\n.tile-sub{font-size:14px;color:var(--ink-2);line-height:1.3}\n.tiles-row{display:flex;flex-direction:column;gap:6px;margin-top:10px}\n.tiles-chips{display:flex;gap:8px;overflow-x:auto;padding-bottom:4px;scrollbar-width:none}\n.tiles-chips .chip{flex:none;white-space:nowrap}");
fs.writeFileSync('public/index.html',s);
const EXPECT='';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v82 ok',h(s),s.length);
