const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='b92f69d98b53377d35bc181e3878ce1483444d78')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v107: uncertain dates kept uncertain. "Sometime next week", "in 2-4 working days", "in the next few days" become a
// window (p.win: from the first day to the end of the last), shown as "Sometime between X and Y", too early to chase
// before it starts, asked about only after it ends. No date at all: a day of your choosing to check back, as your own
// step, which never counts against them. ----
R("  var wdName=false,day=null,by=false,m,T=\"(\\\\d{1,2})(?:[:.](\\\\d{2}))? ?(am|pm|a\\\\.m\\\\.|p\\\\.m\\\\.)?\";",
  "  var wdName=false,day=null,by=false,wstart=null,m,T=\"(\\\\d{1,2})(?:[:.](\\\\d{2}))? ?(am|pm|a\\\\.m\\\\.|p\\\\.m\\\\.)?\";");
R("    else if((m=s.match(/\\b(?:in|within) (\\d+) ?(?:-|–|to|or) ?(\\d+) (working |business )?days\\b/))){day=m[3]?wdFrom(base,+m[2]):add(+m[2]);by=true}",
  "    else if((m=s.match(/\\b(?:in|within) (\\d+) ?(?:-|–|to|or) ?(\\d+) (working |business )?days\\b/))){day=m[3]?wdFrom(base,+m[2]):add(+m[2]);wstart=m[3]?wdFrom(base,+m[1]):add(+m[1]);by=true}\n    else if(/\\b(?:in|over) (?:the )?next (?:few|couple of) days\\b|\\bin a (?:few|couple of) days\\b|\\bin a day or two\\b|\\bnext few days\\b/.test(s)){wstart=add(1);day=add(/\\bcouple\\b|\\bday or two\\b/.test(s)?2:3);by=true}\n    else if(/\\b(?:sometime |later |some point )?(?:this|the coming) week\\b/.test(s)&&!/\\bend of (the |this )?week\\b/.test(s)&&base.getDay()%6){wstart=/\\blater\\b/.test(s)?add(1):base;day=nextWd(5);if(day<wstart)day=wstart;by=true}\n    else if(/\\bearly next week\\b/.test(s)){var enw=base.getDay();wstart=add(((1-enw+7)%7)||7);day=new Date(wstart);day.setDate(day.getDate()+2);by=true}");
R("    else if(/\\bnext week\\b/.test(s)){var nwd=base.getDay();day=add(nwd===6?6:nwd===0?5:((5-nwd+7)%7)+7);by=true}",
  "    else if(/\\bnext week\\b/.test(s)){var nwd=base.getDay();day=add(nwd===6?6:nwd===0?5:((5-nwd+7)%7)+7);wstart=new Date(day);wstart.setDate(wstart.getDate()-4);if(/\\b(?:later|end of|late)\\b[^.]{0,8}\\bnext week\\b/.test(s)){wstart.setDate(wstart.getDate()+2)}by=true}");
R("  var label=from?(dl+\", \"+(to?from+\"–\"+to:(byTime?\"by \":\"\")+from)):(by?\"By \"+(dl===\"Today\"||dl===\"Tomorrow\"?dl.toLowerCase():dl):dl+\", any time\");\n  return {when:from?\"slot\":(by?\"by\":\"slot\"),date:ymdL(day),from:from||\"\",to:to||\"\",label:label};",
  "  var label=from?(dl+\", \"+(to?from+\"–\"+to:(byTime?\"by \":\"\")+from)):(by?\"By \"+(dl===\"Today\"||dl===\"Tomorrow\"?dl.toLowerCase():dl):dl+\", any time\");\n  if(wstart&&!from&&wstart<day)label=\"Sometime between \"+(sameDay(wstart,base)?\"today\":fmtDay(wstart))+\" and \"+fmtDay(day);\n  var out={when:from?\"slot\":(by?\"by\":\"slot\"),date:ymdL(day),from:from||\"\",to:to||\"\",label:label};\n  if(wstart&&!from&&wstart<day)out.wstart=ymdL(wstart);\n  return out;");
R("  var ymd=w.date.split(\"-\").map(Number),start=new Date(ymd[0],ymd[1]-1,ymd[2]),end=null,allDay=!w.from;\n  if(w.from){var a=w.from.split(\":\");start.setHours(+a[0],+a[1]);if(w.to){var b=w.to.split(\":\"),e=new Date(start);e.setHours(+b[0],+b[1]);if(e>start)end=e.toISOString()}}\n  var named=(f&&f.party)?\"\":pNamed(s.slice(0,vm.index));",
  "  var ymd=w.date.split(\"-\").map(Number),start=new Date(ymd[0],ymd[1]-1,ymd[2]),end=null,allDay=!w.from,win=false;\n  if(w.from){var a=w.from.split(\":\");start.setHours(+a[0],+a[1]);if(w.to){var b=w.to.split(\":\"),e=new Date(start);e.setHours(+b[0],+b[1]);if(e>start)end=e.toISOString()}}\n  if(w.wstart&&!w.from){var ws=w.wstart.split(\"-\").map(Number),wl=new Date(start);wl.setHours(23,59,59,999);start=new Date(ws[0],ws[1]-1,ws[2]);end=wl.toISOString();win=true}\n  var named=(f&&f.party)?\"\":pNamed(s.slice(0,vm.index));");
R("  var pr={said:cap1(clause0.replace(/[,\\s]+$/,\"\")),party:(f&&f.party&&!/^the /.test(f.party)?f.party:(f&&f.party)?cap1(f.party.replace(/^the /,\"\")):named?named:(f&&f.resp===\"landlord\"?\"Landlord\":\"\")),dueAt:start.toISOString(),dueEnd:end,allDay:allDay,by:w.when===\"by\",ref:(f&&f.ref)||\"\"};",
  "  var pr={said:cap1(clause0.replace(/[,\\s]+$/,\"\")),party:(f&&f.party&&!/^the /.test(f.party)?f.party:(f&&f.party)?cap1(f.party.replace(/^the /,\"\")):named?named:(f&&f.resp===\"landlord\"?\"Landlord\":\"\")),dueAt:start.toISOString(),dueEnd:end,allDay:allDay,by:w.when===\"by\"&&!win,ref:(f&&f.ref)||\"\"};if(win)pr.win=true;");
R("var sp=t.sugP,spr={id:uid(),said:sp.said,party:sp.party,dueAt:sp.dueAt,dueEnd:sp.dueEnd,allDay:sp.allDay,by:sp.by,ref:sp.ref,status:\"open\",loggedAt:nowIso(),src:sp.fromMsg&&!sp.typed?\"message\":\"sentence\"};",
  "var sp=t.sugP,spr={id:uid(),said:sp.said,party:sp.party,dueAt:sp.dueAt,dueEnd:sp.dueEnd,allDay:sp.allDay,by:sp.by,ref:sp.ref,status:\"open\",loggedAt:nowIso(),src:sp.fromMsg&&!sp.typed?\"message\":\"sentence\"};if(sp.win)spr.win=true;");
R("  var start=new Date(p.dueAt), end;\n  if(p.allDay){end=new Date(start);end.setHours(23,59,59,999)}",
  "  var start=new Date(p.dueAt), end;\n  if(p.win&&p.dueEnd){end=new Date(p.dueEnd)}\n  else if(p.allDay){end=new Date(start);end.setHours(23,59,59,999)}");
R("  if(!w)return \"No date given\";\n  if(p.by)return \"By \"+fmtDay(w.start);",
  "  if(!w)return \"No date given\";\n  if(p.win)return \"Sometime between \"+fmtDay(w.start)+\" and \"+fmtDay(w.end);\n  if(p.by)return \"By \"+fmtDay(w.start);");
R("  if(ph===\"check\")return askFor(p)[0];\n  if(ph===\"now\")return (p.by||p.allDay)&&!pVisit(p)?\"Due today\":\"Happening now\";",
  "  if(ph===\"check\")return askFor(p)[0];\n  if(p.win&&(ph===\"now\"||ph===\"soon\"))return \"Due by \"+fmtDay(w.end);\n  if(ph===\"now\")return (p.by||p.allDay)&&!pVisit(p)?\"Due today\":\"Happening now\";");
R("  if(p.by||p.allDay)return \"You can put this down until \"+fmtDay(w.start)+\".\";",
  "  if(p.win)return \"They didn’t give a day, so Sorted waits until \"+fmtDay(w.end)+\" before it asks.\";\n  if(p.by||p.allDay)return \"You can put this down until \"+fmtDay(w.start)+\".\";");
R("  }else if(!pVisit(p)){\n    h+='<p>'+esc(p.by||p.allDay?\"Due by the end of \"",
  "  }else if(p.win){\n    h+='<p>They said '+esc(whenText(p).replace(/^Sometime/,\"sometime\"))+', without a firm day. If it hasn’t happened by '+esc(fmtDay(window_(p).end))+', Sorted will ask you.</p><button class=\"btn primary block\" data-a=\"kept\">'+esc(askFor(p)[1]===\"Yes\"?\"It’s happened\":askFor(p)[1])+'</button><button class=\"btn block\" data-a=\"rebook\">They’ve given a firm date</button>';\n  }else if(!pVisit(p)){\n    h+='<p>'+esc(p.by||p.allDay?\"Due by the end of \"");
R("c.p=[p.said,p.party||\"\",p.dueAt||null,p.dueEnd||null,p.allDay?1:0,p.ref||\"\",p.loggedAt||null,p.by?1:0];",
  "c.p=[p.said,p.party||\"\",p.dueAt||null,p.dueEnd||null,p.allDay?1:0,p.ref||\"\",p.loggedAt||null,p.by?1:0,p.win?1:0];");
R("var p=c.p?{said:c.p[0],party:c.p[1],dueAt:c.p[2],dueEnd:c.p[3],allDay:!!c.p[4],ref:c.p[5],loggedAt:c.p[6],by:!!c.p[7],status:\"open\"}:null;",
  "var p=c.p?{said:c.p[0],party:c.p[1],dueAt:c.p[2],dueEnd:c.p[3],allDay:!!c.p[4],ref:c.p[5],loggedAt:c.p[6],by:!!c.p[7],win:!!c.p[8],status:\"open\"}:null;");
R("function corrDue(w){var ymd=w.date.split(\"-\").map(Number),start=new Date(ymd[0],ymd[1]-1,ymd[2]),end=null;\n  if(w.from){var a=w.from.split(\":\");start.setHours(+a[0],+a[1]);if(w.to){var b=w.to.split(\":\"),e=new Date(start);e.setHours(+b[0],+b[1]);if(e>start)end=e.toISOString()}}\n  return {dueAt:start.toISOString(),dueEnd:end,allDay:!w.from,by:w.when===\"by\"}}",
  "function corrDue(w){var ymd=w.date.split(\"-\").map(Number),start=new Date(ymd[0],ymd[1]-1,ymd[2]),end=null,win=false;\n  if(w.from){var a=w.from.split(\":\");start.setHours(+a[0],+a[1]);if(w.to){var b=w.to.split(\":\"),e=new Date(start);e.setHours(+b[0],+b[1]);if(e>start)end=e.toISOString()}}\n  if(w.wstart&&!w.from){var ws=w.wstart.split(\"-\").map(Number),wl=new Date(start);wl.setHours(23,59,59,999);start=new Date(ws[0],ws[1]-1,ws[2]);end=wl.toISOString();win=true}\n  return {dueAt:start.toISOString(),dueEnd:end,allDay:!w.from,by:w.when===\"by\"&&!win,win:win}}");
R("var np=Object.assign({},p,{id:uid(),status:\"open\",closedAt:undefined,dueAt:c.dueAt,dueEnd:c.dueEnd,allDay:c.allDay,by:c.by,loggedAt:at});",
  "var np=Object.assign({},p,{id:uid(),status:\"open\",closedAt:undefined,dueAt:c.dueAt,dueEnd:c.dueEnd,allDay:c.allDay,by:c.by,win:!!c.win,loggedAt:at});");
R("    else if(p){p.dueAt=c.dueAt;p.dueEnd=c.dueEnd;p.allDay=c.allDay;p.by=c.by;t.board=\"waiting\";",
  "    else if(p){p.dueAt=c.dueAt;p.dueEnd=c.dueEnd;p.allDay=c.allDay;p.by=c.by;p.win=!!c.win;t.board=\"waiting\";");
R("function corrWhen(c){return whenText(c).replace(/, any time$/,\"\")}",
  "function corrWhen(c){return whenText({dueAt:c.dueAt,dueEnd:c.dueEnd,allDay:c.allDay,by:c.by,win:c.win}).replace(/, any time$/,\"\")}");
R("  var rno=frRenewOnly(t);h+='<div class=\"row eq\">'+(dl?",
  "  var frnd=!pk&&!dl&&!pso&&t.mode===\"call\"&&!p&&FR_NODATE.test(said)&&!PMISS.test(said);\n  if(frnd)h+='<div class=\"stack-s fr-check\"><p class=\"h3\" style=\"margin:0\">Or pick a day to check back</p><p class=\"muted\" style=\"margin:0;font-size:15px\">Your own reminder, not their promise. It won’t count against '+esc(who||\"them\")+'.</p><div class=\"chips\">'+[[3,\"In 3 days\"],[7,\"In a week\"],[14,\"In 2 weeks\"]].map(function(x){return '<button class=\"chip\" data-a=\"fr-check\" data-d=\"'+x[0]+'\">'+x[1]+'</button>'}).join(\"\")+'</div></div>';\n  var rno=frRenewOnly(t);h+='<div class=\"row eq\">'+(dl?");
R("    case \"fr-remind\":if(t){",
  "    case \"fr-check\":if(t){var fcd=+b.getAttribute(\"data-d\")||7,fcw=frParty(t)||(t.facts&&t.facts.party)||pNamed(String(t.said||\"\").replace(/[’‘]/g,\"'\").split(/\\b(?:said|told|promised|agreed)\\b/)[0]+\" \")||\"them\",fcday=addDays(new Date(),fcd);fcday.setHours(0,0,0,0);\n      if(!t.moves)t.moves=[];var fcm={id:uid(),what:\"Check back with \"+fcw+\" if nothing has happened\",act:moveAct(\"check back\").key,dueAt:fcday.toISOString(),dueEnd:null,allDay:true,by:true,status:\"open\",loggedAt:nowIso(),chosen:true};\n      t.moves.push(fcm);t.board=\"yours\";t.frNew=false;log(t,\"Your move: check back with \"+fcw+\" if nothing has happened (by \"+fmtDay(fcday)+\"). The day was your choice; \"+fcw+\" didn’t give one.\");var fca=defaultEmail(t);commit();window.scrollTo(0,0);if(fca)toast(\"Sorted will email you a reminder. You can turn it off.\")}break;\n    case \"fr-remind\":if(t){");
R("if(t.titleFb&&spr.party){t.title=spr.party+\" · \"+fmtDay(new Date(spr.dueAt)).replace(\",\",\"\");t.titleFb=false}",
  "if(t.titleFb&&spr.party){t.title=spr.party+\" · \"+(spr.win?\"by \"+fmtDay(new Date(spr.dueEnd)):fmtDay(new Date(spr.dueAt))).replace(\",\",\"\");t.titleFb=false}");
fs.writeFileSync('public/index.html',s);
const EXPECT='a67be56623578140247bee3124bd1a657b7b2158';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v107 ok',h(s),s.length);
