const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='584208a759a8d287d2c8464a1bb7499ee023fca6')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v122: one function, clearLocalUserData(), removes what Sorted keeps on this phone for a person, and is called
// from sign-out, account deletion, the move from a guest to an email account, draft expiry (the draft is removed, not
// ignored), a failed photo read (the words go, the judgement stays) and Settings. Changing the kind of case keeps the
// other kind's answers dormant on the case (t.kept) instead of deleting them. ----
R("var S={tasks:[],moments:[],view:{name:\"home\"},draft:{},shared:null,user:null,booting:true,offline:false};\n",
  "var S={tasks:[],moments:[],view:{name:\"home\"},draft:{},shared:null,user:null,booting:true,offline:false};\n/* v122: the one place that removes what Sorted keeps on this phone for a person: the copy of their cases and moves, drafts,\n   carried copies, a shared-in text, the step queue, start choices, per-case notes and anything read from a photo. Called at\n   sign-out, when the account is deleted, when a guest moves to an email account, when a draft expires, and from Settings.\n   Preferences that say nothing about a case (appearance, usage records on or off, notices seen) stay. */\nvar LOCAL_KEYS=[\"sorted.evq\",\"sorted.carry\",\"sorted.carrytok\",\"sorted.moment\",\"sorted.sharedIn\",\"sorted.cap82\",\"sorted.carry82\",\"cap90.choice\"];\nfunction clearLocalUserData(uid,opt){\n  opt=opt||{};\n  [localStorage,sessionStorage].forEach(function(st){try{\n    var ks=[];for(var i=0;i<st.length;i++)ks.push(st.key(i));\n    ks.forEach(function(k){\n      if(!k)return;\n      var mine=/^sorted\\.(?:cache|draft)\\./.test(k);\n      if(mine){var own=uid&&(k===\"sorted.cache.\"+uid||k===\"sorted.draft.\"+uid);if(opt.others?!own:own)st.removeItem(k);return}\n      if(opt.others)return;\n      if(/^sorted\\.local\\./.test(k)){st.removeItem(k);return}\n      if(LOCAL_KEYS.indexOf(k)>=0&&!(opt.keepCarry&&/^sorted\\.carry(?:tok)?$/.test(k)))st.removeItem(k);\n    });\n  }catch(e){}});\n  if(opt.others)return;\n  EVQ=[];S.draft={};S.pendingMom=null;S.sharedIn=null;S.delUndo=null;S.evUndo=null;S.caseMail=null;S.notes=null;S.inbox=[];S.found=null;S.ai=null;\n  try{if(window.__cap87reset)window.__cap87reset();if(window.__cap90reset)window.__cap90reset()}catch(e){}\n}\n");
R("var swipe=function(){try{localStorage.removeItem(\"sorted.cache.\"+suid);[\"sorted.evq\",\"sorted.carry\",\"sorted.carrytok\",\"sorted.moment\",\"sorted.sharedIn\",\"sorted.cap82\",\"sorted.carry82\"].forEach(function(k){localStorage.removeItem(k);sessionStorage.removeItem(k)})}catch(e){}};swipe();",
  "var swipe=function(){clearLocalUserData(suid)};swipe();");
R("try{localStorage.removeItem(cacheKey());Object.keys(localStorage).forEach(function(k){if(k.indexOf(\"sorted.local.\")===0)localStorage.removeItem(k)})}catch(e){}S.tasks=[];sb.auth.signOut()",
  "var wuid=S.user?S.user.id:\"none\";clearLocalUserData(wuid);S.tasks=[];S.moments=[];sb.auth.signOut().finally(function(){clearLocalUserData(wuid)})");
R("case \"claim-signin\":{try{localStorage.setItem(\"sorted.carry\",JSON.stringify(S.tasks.map(clean)))}catch(e){}var cem=d.cemail;",
  "case \"claim-signin\":{try{localStorage.setItem(\"sorted.carry\",JSON.stringify(S.tasks.map(clean)))}catch(e){}var cem=d.cemail;clearLocalUserData(S.user?S.user.id:\"none\",{keepCarry:true});");
R("  S.tasks=cacheRead();momSplit();momPendingBoot();giRestore();",
  "  clearLocalUserData(id,{others:true});\n  S.tasks=cacheRead();momSplit();momPendingBoot();giRestore();");
R("function draftLoad(){try{var o=JSON.parse(localStorage.getItem(draftKey())||\"null\");if(!o||Date.now()-(o.at||0)>7*DAY)return null;",
  "function draftLoad(){try{var o=JSON.parse(localStorage.getItem(draftKey())||\"null\");if(!o)return null;if(Date.now()-(o.at||0)>7*DAY){draftDrop();return null}");
R("    if(dr.status===\"failed\"){docTrack(\"document_read_failed\",",
  "    if(dr.status===\"failed\"||dr.status===\"notpcn\"){dr.raw=\"\";dr.pcn=null}\n    if(dr.status===\"failed\"){docTrack(\"document_read_failed\",");
R("<p class=\"muted\" style=\"margin:0;font-size:15px\">Kept on this phone only.</p></section>';\n  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Usage records</p>",
  "<p class=\"muted\" style=\"margin:0;font-size:15px\">Kept on this phone only.</p></section>';\n  h+='<section class=\"sheet stack-s\"><p class=\"h3\">This phone</p><p>Sorted keeps a copy of your cases on this phone so they open quickly and work offline. What is saved on Sorted’s servers is not affected by this.</p>'+(pendingRecs().length?'<p class=\"muted\" style=\"margin:0;font-size:15px\">A change is still being saved. Once it has reached your account, you can remove the copy here.</p>':'<button class=\"btn\" data-a=\"local-reset\">Remove the copy from this phone</button><p class=\"muted\" style=\"margin:0;font-size:15px\">Removes the copy, drafts and anything read from a photo, then reloads your cases from your account.</p>')+'</section>';\n  h+='<section class=\"sheet stack-s\"><p class=\"h3\">Usage records</p>");
R(".acct112-nav{display:flex;flex-wrap:wrap;gap:8px}",
  ".acct112-nav{display:flex;flex-wrap:wrap;gap:8px}\n.cap122-where{font-size:14px;color:var(--ink-2)}");
R("    case \"steps-toggle\":",
  "    case \"local-reset\":{if(pendingRecs().length){toast(\"Wait until saving has finished.\");break}var luid=S.user?S.user.id:\"none\";clearLocalUserData(luid);S.tasks=[];S.moments=[];toast(\"Removed from this phone. Reloading your cases.\");setTimeout(function(){location.reload()},400);break}\n    case \"steps-toggle\":");
R("    if(nk===\"fix\"){t.mode=\"fix\";t.fix={step:\"what\",checks:{}};var ki=thingOf(String(t.said||t.title||\"\"));if(ki)t.fix.item=ki;t.renew=null}\n    else if(nk===\"do\"){t.mode=\"do\";t.fix=null;t.renew=null}\n    else{t.mode=\"call\";t.fix=null;t.renew=null}\n    delete t.turn;delete t.goalP;t.frNew=false;",
  "    /* v122: nothing known is deleted. The answers that belong to the old kind are kept on the case (t.kept) and come back if the\n       person returns to that kind; promises, facts, references, messages, playbook counts and the history are never touched. */\n    t.kept=t.kept||{};t.kept[ok0]={fix:t.fix||null,renew:t.renew||null,at:nowIso()};\n    var kb=t.kept[nk]||{};\n    if(nk===\"fix\"){t.mode=\"fix\";t.fix=kb.fix||{step:\"what\",checks:{}};if(!t.fix.item){var ki=thingOf(String(t.said||t.title||\"\"));if(ki)t.fix.item=ki}t.renew=kb.renew||null}\n    else if(nk===\"do\"){t.mode=\"do\";t.fix=null;t.renew=kb.renew||null}\n    else{t.mode=\"call\";t.fix=null;t.renew=kb.renew||null}\n    delete t.goalP;t.frNew=false;");
R("<p class=\"muted\" style=\"font-size:16px\">Nothing is lost: your words, messages and history stay. Sorted changes only which questions it asks and what it shows next.</p>",
  "<p class=\"muted\" style=\"font-size:16px\">Nothing is lost: your words, messages, promises, references and history stay, and the answers you gave for this kind are kept in case you come back to it. Sorted changes only which questions it asks and what it shows next.</p>");
R("function mvLink(it,a){var n=(a&&a.nation)||\"en\";return (MV_NAT[n]&&MV_NAT[n][it.link])||MV_LINK[it.link]||null}",
  "/* v122: a link that differs between the four nations is shown only once the person has said where the new home is.\n   Sorted never picks a nation for them. */\nfunction mvNatOnly(key){for(var n in MV_NAT)if(MV_NAT[n]&&MV_NAT[n][key])return true;return false}\nfunction mvLink(it,a){var n=(a&&a.nation)||\"\";if(!n){return mvNatOnly(it.link)?null:(MV_LINK[it.link]||null)}return (MV_NAT[n]&&MV_NAT[n][it.link])||MV_LINK[it.link]||null}");
R("function momLinkA(it,cls,a){var L=it.link?mvLink(it,a):null;return L?'<a class=\"'+cls+'\" href=\"'+L[0]+'\" target=\"_blank\" rel=\"noopener\">'+esc(L[1])+'</a>':''}",
  "function momLinkA(it,cls,a){var L=it.link?mvLink(it,a):null;if(!L&&it.link&&!(a&&a.nation)&&mvNatOnly(it.link))return '<span class=\"cap122-where\">Say where your new home is to see the official page.</span>';return L?'<a class=\"'+cls+'\" href=\"'+L[0]+'\" target=\"_blank\" rel=\"noopener\">'+esc(L[1])+'</a>':''}");
R("<p class=\"note cap108-nation\" style=\"margin:0\">Which nation is the new home in? The official links differ. <button class=\"link\" data-a=\"mom-edit\" style=\"display:inline;min-height:0;padding:0\">Say where</button></p>",
  "<p class=\"note cap108-nation\" style=\"margin:0\">Where is your new home? The official pages for the licence, voting, the GP and the council differ between England, Wales, Scotland and Northern Ireland, so Sorted shows those links only once you say. <button class=\"link\" data-a=\"mom-edit\" style=\"display:inline;min-height:0;padding:0\">Say where</button></p>");
R("  h+='<div class=\"stack-s\"><p class=\"h3\" style=\"margin:0\">Where is the new home?</p><p class=\"muted\" style=\"margin:0;font-size:15px\">The official pages for your licence, voting, the GP and the council differ between the four nations.</p>'+momChips(\"mv-nation\",MV_NATIONS,a.nation||\"\")+'</div>';\n",
  "");
R("h+='<div class=\"stack-s\"><p class=\"h3\" style=\"margin:0\">Are you renting or buying?</p>'+momChips(\"mv-tenure\",[[\"rent\",\"Renting\"],[\"buy\",\"Buying\"],[\"other\",\"Neither, or not sure\"]],a.tenure||\"rent\")+'</div>';",
  "  h+='<div class=\"stack-s\"><p class=\"h3\" style=\"margin:0\">Where is your new home?</p><p class=\"muted\" style=\"margin:0;font-size:15px\">The official pages for your licence, voting, the GP and the council differ between the four nations, so Sorted won’t show those until you say.</p>'+momChips(\"mv-nation\",MV_NATIONS,a.nation||\"\")+'</div>';\n  h+='<div class=\"stack-s\"><p class=\"h3\" style=\"margin:0\">Are you renting or buying?</p>'+momChips(\"mv-tenure\",[[\"rent\",\"Renting\"],[\"buy\",\"Buying\"],[\"other\",\"Neither, or not sure\"]],a.tenure||\"rent\")+'</div>';");
R("<nav class=\"acct112-nav\" role=\"tablist\" aria-label=\"Account, Settings, Help & About\">'+TABS.map(function(x){return '<button class=\"btn quiet'+(tab===x[0]?' on':'')+'\" role=\"tab\" aria-selected=\"'+(tab===x[0])+'\" aria-controls=\"'+x[0]+'\" data-a=\"acct-jump\" data-v=\"'+x[0]+'\">'+x[1]+'</button>'}).join(\"\")+'</nav>';",
  "<nav class=\"acct112-nav\" aria-label=\"Account pages\">'+TABS.map(function(x){return '<button class=\"btn quiet'+(tab===x[0]?' on':'')+'\"'+(tab===x[0]?' aria-current=\"page\"':'')+' data-a=\"acct-jump\" data-v=\"'+x[0]+'\">'+x[1]+'</button>'}).join(\"\")+'</nav>';");
R("<section class=\"stack acct112-part\" id=\"acct-you\" role=\"tabpanel\" aria-labelledby=\"acct-you-h\">",
  "<section class=\"stack acct112-part\" id=\"acct-you\" aria-labelledby=\"acct-you-h\">");
R("<section class=\"stack acct112-part\" id=\"acct-settings\" role=\"tabpanel\" aria-labelledby=\"acct-settings-h\">",
  "<section class=\"stack acct112-part\" id=\"acct-settings\" aria-labelledby=\"acct-settings-h\">");
R("<section class=\"stack acct112-part\" id=\"help\" role=\"tabpanel\" aria-labelledby=\"help-h\">",
  "<section class=\"stack acct112-part\" id=\"help\" aria-labelledby=\"help-h\">");
R("Nothing is saved until you press Start, and nothing on a case changes without your tap.",
  "Nothing is saved until you press Start. Sorted doesn’t turn an uncertain suggestion into a confirmed fact until you confirm it.");
R("If it’s working, you can finish this case. If not, Sorted keeps count and holds them to the next visit.",
  "If it’s working, you can finish this case. If not, Sorted keeps count and brings the next visit back when it’s due.");
R("Sorted keeps your cases in London to hold them and remind you.",
  "Sorted keeps your cases in London so they are there when you come back, and to remind you.",2);
fs.writeFileSync('public/index.html',s);
const EXPECT='1b0d3d37bf17480842cd087b2fb9e4bba0bc9c57';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v122 ok',h(s),s.length);
