const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='58ca38672e33e46a7aaf763610ad9eeb8104c86f')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v119 (Phase 3, part 2): a draft is kept on this phone until Start ("Continue draft" on Home, the box or the
// guided form refilled after a reload); the kind of case can be changed in place (a promise, a repair, your own
// task) without starting again. ----
R("var SORTED_V=\"v118\"",
  "var SORTED_V=\"v119\"");
R("function giForget(){",
  "/* v119: a draft is kept on this phone until Start, so a stray tap, a failed save or a lost connection doesn't lose what was typed */\nfunction draftKey(){return \"sorted.draft.\"+(S.user?S.user.id:\"none\")}\nfunction draftSave(){try{var d=S.draft||{},who=$(\"#gi-who\"),what=$(\"#gi-what\"),o={text:String(d.casetext||\"\"),gk:d.gk||\"\",who:who?String(who.value||\"\"):\"\",what:what?String(what.value||\"\"):\"\",at:Date.now()};if(!o.text.trim()&&!o.who.trim()&&!o.what.trim()){localStorage.removeItem(draftKey());return}localStorage.setItem(draftKey(),JSON.stringify(o))}catch(e){}}\nfunction draftLoad(){try{var o=JSON.parse(localStorage.getItem(draftKey())||\"null\");if(!o||Date.now()-(o.at||0)>7*DAY)return null;if(!String(o.text||\"\").trim()&&!String(o.who||\"\").trim()&&!String(o.what||\"\").trim())return null;return o}catch(e){return null}}\nfunction draftDrop(){try{localStorage.removeItem(draftKey())}catch(e){}}\nfunction draftWords(o){var w=String(o.text||\"\").trim()||[o.who,o.what].filter(function(x){return String(x||\"\").trim()}).join(\": \");return w.length>70?w.slice(0,70).replace(/\\s+\\S*$/,\"\")+\"…\":w}\nfunction draftBlock(){if(S.composeOpen||S.newOpen||!S.tasks.length)return \"\";var o=draftLoad();if(!o)return \"\";return '<section class=\"sheet stack-s draft119\" aria-labelledby=\"draft119-h\"><p class=\"h3\" id=\"draft119-h\" style=\"margin:0\">You started writing something</p><p class=\"muted\" style=\"margin:0;font-size:15px\">“'+esc(draftWords(o))+'”. Nothing is saved until you press Start.</p><div class=\"row\"><button class=\"btn primary\" data-a=\"draft-go\">Continue draft</button><button class=\"btn quiet\" data-a=\"draft-drop\">Discard it</button></div></section>'}\nfunction giForget(){");
R("  if(el.name===\"casetext\"&&S.draft.caseErr){S.draft.caseErr=\"\";var cer=el.form&&el.form.querySelector(\".err\");if(cer)cer.remove()}",
  "  if(el.name===\"casetext\"&&S.draft.caseErr){S.draft.caseErr=\"\";var cer=el.form&&el.form.querySelector(\".err\");if(cer)cer.remove()}\n  if(el.name===\"gi-who\")S.draft.gwho=el.value;if(el.name===\"gi-what\")S.draft.gwhat=el.value;\n  if(el.name===\"casetext\"||el.name===\"gi-who\"||el.name===\"gi-what\")draftSave();");
R("  if(!carry){if(k&&!(S.draft&&S.draft.gk))giForget();return}  /* a reload restores saved work only, never a half-done start */",
  "  var dr0=draftLoad();if(dr0&&dr0.text&&!(S.draft&&S.draft.casetext))S.draft=Object.assign({},S.draft||{},{casetext:dr0.text});\n  if(!carry){if(k&&!(S.draft&&S.draft.gk))giForget();return}  /* a reload restores saved work only, never a half-done start */");
R("      h+='<section class=\"home111-new'+(nOpen?' open':'')+'\" id=\"home111-new\" aria-labelledby=\"home111-new-h\"><h2 class=\"h2\" id=\"home111-new-h\">Sort something new</h2>",
  "      h+=draftBlock();\n      h+='<section class=\"home111-new'+(nOpen?' open':'')+'\" id=\"home111-new\" aria-labelledby=\"home111-new-h\"><h2 class=\"h2\" id=\"home111-new-h\">Sort something new</h2>");
R("  g.f.forEach(function(x,i){var px=ex&&ex.ph&&ex.ph[x[0]]||x[2],vx=ex&&ex.val&&ex.val[x[0]]||\"\";",
  "  g.f.forEach(function(x,i){var px=ex&&ex.ph&&ex.ph[x[0]]||x[2],vx=ex&&ex.val&&ex.val[x[0]]||(x[0]===\"who\"?S.draft.gwho:x[0]===\"what\"?S.draft.gwhat:\"\")||\"\";");
R("    case \"gi-back\":{S.draft={};",
  "    case \"draft-go\":{var dgo=draftLoad();if(!dgo)break;S.newOpen=true;S.composeOpen=true;S.draft=dgo.gk&&GI[dgo.gk]?{gk:dgo.gk,gwho:dgo.who,gwhat:dgo.what,casetext:dgo.text}:{casetext:dgo.text||[dgo.who,dgo.what].filter(Boolean).join(\" \")};try{if(dgo.gk)sessionStorage.setItem(\"sorted.cap82\",dgo.gk)}catch(e){}render();setTimeout(function(){var df=$(\"#gi-what\")||$(\"#f-case\");if(df){df.focus({preventScroll:true});df.scrollIntoView({block:\"center\"})}},60);break}\n    case \"draft-drop\":{draftDrop();render();toast(\"Draft discarded\");break}\n    case \"gi-back\":{S.draft={};");
R("  momAttach(t);giForget();S.newOpen=false;t.frNew=true;",
  "  momAttach(t);giForget();draftDrop();S.newOpen=false;t.frNew=true;");
R("S.draft={casetext:gtx,gfrom:gk2,gwho:gk2!==\"fix\"?gv.who:\"\",gwhat:gv.what||\"\"};render();",
  "S.draft={casetext:gtx,gfrom:gk2,gwho:gk2!==\"fix\"?gv.who:\"\",gwhat:gv.what||\"\"};draftSave();render();");
R("if(view.name!==\"home\")S.composeOpen=false;S.view=view;S.draft={};render();",
  "if(view.name!==\"home\")S.composeOpen=false;S.view=view;S.draft={};if(view.name===\"home\"&&S.composeOpen){var dr1=draftLoad();if(dr1){S.draft={casetext:dr1.text||\"\",gwho:dr1.who||\"\",gwhat:dr1.what||\"\"};if(dr1.gk&&GI[dr1.gk])S.draft.gk=dr1.gk}}render();");
R("  if(s!==\"done\"&&!t.example)h+='<button class=\"link\" data-a=\"panel\" data-p=\"correct\">Correct a detail (the company, the reference, the amount, the date)</button>';",
  "  if(s!==\"done\"&&!t.example)h+='<button class=\"link\" data-a=\"panel\" data-p=\"correct\">Correct a detail (the company, the reference, the amount, the date)</button>';\n  if(s!==\"done\"&&!t.example&&!t.cf&&!pkOn(t))h+='<button class=\"link\" data-a=\"panel\" data-p=\"kind\">Change the kind of case (a promise, a repair, your own task)</button>';");
R("  if(S.view.panel===\"rename\")return h+renameForm(t)+'</main>';",
  "  if(S.view.panel===\"rename\")return h+renameForm(t)+'</main>';\n  if(S.view.panel===\"kind\")return h+kindForm(t)+'</main>';");
R("function renameForm(t){",
  "/* v119: the kind of case can be corrected in place. Three kinds: someone else owes the next move (mode call), something needs fixing (fix), your own task (do). */\nvar KINDS=[[\"call\",\"Someone else owes me the next move\",\"A promise, a refund, a reply, a decision, a letter to answer.\"],[\"fix\",\"Something needs fixing\",\"A repair: Sorted asks what it is and works out who should fix it.\"],[\"do\",\"Something I need to do myself\",\"Your own task with a date; nobody to chase.\"]];\nfunction kindOf(t){return t.mode===\"fix\"?\"fix\":t.mode===\"do\"?\"do\":\"call\"}\nfunction kindForm(t){\n  var cur=kindOf(t),pick=S.draft.kind||cur;\n  return '<section class=\"sheet stack\"><div class=\"stack-s\"><p class=\"eyebrow\">The kind of case</p><h2 class=\"h2\">What kind of case is this?</h2><p class=\"muted\" style=\"font-size:16px\">Nothing is lost: your words, messages and history stay. Sorted changes only which questions it asks and what it shows next.</p></div><form class=\"stack-s\" data-f=\"kind\"><div class=\"chips\" role=\"group\" aria-label=\"Kind of case\">'+KINDS.map(function(k){return '<button type=\"button\" class=\"chip\" data-a=\"d\" data-k=\"kind\" data-v=\"'+k[0]+'\" aria-pressed=\"'+(pick===k[0])+'\">'+esc(k[1])+'</button>'}).join(\"\")+'</div><p class=\"muted\" style=\"margin:0;font-size:15px\">'+esc((KINDS.filter(function(k){return k[0]===pick})[0]||KINDS[0])[2])+'</p>'+(S.draft.err?'<p class=\"err\">'+esc(S.draft.err)+'</p>':'')+'<div class=\"row\"><button class=\"btn primary\" type=\"submit\">'+(pick===cur?\"Keep it as it is\":\"Change it\")+'</button><button class=\"btn\" type=\"button\" data-a=\"panel\" data-p=\"\">Cancel</button></div></form></section>';\n}\nfunction renameForm(t){");
R("  if(k===\"rename\"){",
  "  if(k===\"kind\"){\n    var nk=S.draft.kind||kindOf(t),ok0=kindOf(t);\n    if(nk===ok0){S.view.panel=null;S.draft={};render();return}\n    var kname=function(x){return (KINDS.filter(function(k){return k[0]===x})[0]||[])[1]||x};\n    if(nk===\"fix\"){t.mode=\"fix\";t.fix={step:\"what\",checks:{}};var ki=thingOf(String(t.said||t.title||\"\"));if(ki)t.fix.item=ki;t.renew=null}\n    else if(nk===\"do\"){t.mode=\"do\";t.fix=null;t.renew=null}\n    else{t.mode=\"call\";t.fix=null;t.renew=null}\n    delete t.turn;delete t.goalP;t.frNew=false;\n    log(t,\"Changed the kind of case from “\"+kname(ok0)+\"” to “\"+kname(nk)+\"”.\");\n    S.view.panel=nk===\"do\"&&!openMove(t)?\"move\":null;S.draft=nk===\"do\"&&!openMove(t)?moveDraft(String(t.title||\"\")):{};commit();window.scrollTo(0,0);toast(\"Changed\");return;\n  }\n  if(k===\"rename\"){");
R("</style>\n</head>\n<body>\n<div class=\"wrap\" id=\"app\"></div>\n<d",
  "</style>\n<style>\n/* v119 */\n.draft119{border-left:4px solid var(--violet,#4F39D9)}\n</style>\n</head>\n<body>\n<div class=\"wrap\" id=\"app\"></div>\n<d");
fs.writeFileSync('public/index.html',s);
const EXPECT='1e74b0f885465f77443c53511b82d8b0568c44f4';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v119 ok',h(s),s.length);
