const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='ee202b9619dc17c5dbfeaa84ceeac389f2272a01')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v154: the saving extraction, step 1. One answer to "where is this record saved?" ----
// syncState(x) and syncOf(t) replace the flag checks in syncText (and its v143 wrapper for a case too big to save) and
// pendingRecs. Test 120 compares syncText, syncAll and pendingRecs with the v153 page on every combination of flags.
const REPS=[["function syncText(t){\n  if(!S.user||!t||t.example)return \"\";\n  if(t._saving)return \"Saving…\";\n  if(t._dirty)return isOffline()?\"Saved on this phone, not yet sent. It sends when you’re back online.\":\"Saved on this phone, not yet sent.\";\n  return t.rev?(S.user.email?\"Saved to your account\":\"Saved to Sorted. You can reopen this case on this browser. Add an email to open it on another device.\"):\"\";\n}\n", "function syncText(t){var o=syncOf(t);if(!o)return \"\";\n  if(o.big)return \"Too big to save: remove a long message from this case, then it saves.\";\n  if(o.st===\"saving\")return \"Saving…\";\n  if(o.st===\"local\")return o.off?\"Saved on this phone, not yet sent. It sends when you’re back online.\":\"Saved on this phone, not yet sent.\";\n  return o.st===\"saved\"?(o.email?\"Saved to your account\":\"Saved to Sorted. You can reopen this case on this browser. Add an email to open it on another device.\"):\"\";\n}\n"], ["var syncText142=syncText;syncText=function(t){if(t&&S.user&&!t.example&&big143(t))return \"Too big to save: remove a long message from this case, then it saves.\";return syncText142(t)};\n", ""], ["function pendingRecs(){return S.tasks.concat(S.moments||[]).filter(function(x){return x._dirty||x._saving})}", "/* v154: one answer to \"where is this record saved?\" (the saving extraction, step 1): none, saving, local (on this\n   phone, not yet sent), saved (the server confirmed a revision) or new; syncOf(t) adds too big, offline and the kind of\n   account. syncText, syncAll, pendingRecs, the sign-out question and the Home sync line all read it. */\nfunction syncState(x){return !x?\"none\":x._saving?\"saving\":x._dirty?\"local\":x.rev?\"saved\":\"new\"}\nfunction syncOf(t){if(!S.user||!t||t.example)return null;return {st:syncState(t),big:big143(t),off:isOffline(),email:!!S.user.email}}\nfunction pendingRecs(){return S.tasks.concat(S.moments||[]).filter(function(x){var st=syncState(x);return st===\"saving\"||st===\"local\"})}"]];
for(const [a,b] of REPS)R(a,b);
s=s.split('SORTED_V="v153"').join('SORTED_V="v154"');
fs.writeFileSync('public/index.html',s);
const EXPECT='6e08ecddc881134f6a5074665447842aa55248e9';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v154 ok',h(s),s.length);
