const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='87ca5c4dcf71389406113b4779d158e525df5c06')throw new Error('base mismatch '+h(s));
function R(a,b){const n=s.split(a).length-1;if(n!==1)throw new Error('match '+n+': '+String(a).slice(0,60));s=s.replace(a,()=>b)}
// ---- v9: sign-in code ----
R("    h+='<section class=\"sheet stack\"><p class=\"h2\">Check your email</p><p>We sent a sign-in link to <span class=\"mono\" style=\"word-break:break-all\">'+esc(d.email)+'</span>. Open it on this phone and tap the link.</p><p class=\"muted\" style=\"font-size:16px\">Nothing there after a few minutes? Look in junk mail, then try again.</p><button class=\"btn block\" data-a=\"resend\">Use a different email</button></section>';","    h+='<section class=\"sheet stack\"><p class=\"h2\">Check your email</p><p>We sent an email to <span class=\"mono\" style=\"word-break:break-all\">'+esc(d.email)+'</span>. Tap the link in it, or type the code from it here.</p>';\n    h+='<form class=\"stack-s\" data-f=\"code\"><label class=\"f\">Code from the email<input type=\"text\" id=\"f-code\" name=\"code\" inputmode=\"numeric\" autocomplete=\"one-time-code\" maxlength=\"10\" value=\"'+esc(d.code||\"\")+'\" class=\"mono\" style=\"letter-spacing:4px;font-size:22px\"></label>'+(d.cerr?'<p class=\"err\">'+esc(d.cerr)+'</p>':'')+'<button class=\"btn primary block\" type=\"submit\"'+(d.cbusy?\" disabled\":\"\")+'>'+(d.cbusy?\"Checking…\":\"Sign in\")+'</button></form>';\n    h+='<p class=\"muted\" style=\"font-size:16px\">Use the newest email. Each new one cancels the one before. Nothing there after a few minutes? Look in junk mail.</p><button class=\"btn block\" data-a=\"resend\">Send a new email or use a different one</button></section>';");
R("We’ll send a link. No password needed.","We’ll email you a link and a code. No password needed.");
R("      if(r.error){d.err=/rate|many|seconds/i.test(r.error.message)?\"Too many links sent. Wait a few minutes and try again.\":","      if(r.error){var wsec=(r.error.message.match(/after (\\d+) seconds/)||[])[1];d.err=wsec?\"Wait \"+wsec+\" seconds, then ask again. Only the newest email works.\":/rate|many|seconds/i.test(r.error.message)?\"Too many emails sent. Wait a minute, then try again. Only the newest email works.\":");
R("      d.sent=true;render();","      d.sent=true;d.code=\"\";d.cerr=\"\";render();");
R("  if(k===\"title\"){\n    d.title=$(\"#f-title\").value;","  if(k===\"code\"){\n    var cv=($(\"#f-code\").value||\"\").replace(/\\D/g,\"\");d.code=cv;\n    if(cv.length<6){d.cerr=\"Type the code from the newest email.\";render();return}\n    d.cerr=\"\";d.cbusy=true;render();\n    sb.auth.verifyOtp({email:d.email,token:cv,type:\"email\"}).then(function(r){\n      d.cbusy=false;\n      if(r.error){d.cerr=/expired|invalid/i.test(r.error.message)?\"That code has expired or was replaced. Use the newest email, or ask for a new one.\":\"That code didn’t work. Check it and try again.\";render();return}\n      if(r.data&&r.data.session)setUser(r.data.session.user);\n    },function(){d.cbusy=false;d.cerr=\"Couldn’t check the code. Check your connection.\";render()});\n    return;\n  }\n  if(k===\"title\"){\n    d.title=$(\"#f-title\").value;");
const EXPECT9=process.env.NOCHECK?null:'2a0706a56f9348b7d3dde0bad9a552e82c8c412d';if(EXPECT9&&h(s)!==EXPECT9)throw new Error('v9 mismatch '+h(s));
fs.writeFileSync('public/index.html',s);console.log('v9 ok',h(s));
