const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='87a4eb9690a9783641afeed10e87fb67d455df0d')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v125 (the remaining-pages review, signed in): forms on a case keep what was typed when you leave; Moving home
// keeps answers after a missing date; case pickers show every case with a search; deletion says what Undo does; a
// parking notice never opens call preparation; a case leads with status and one next step, explanations after the
// action; the document door has its own heading and the first-page limit; one set of choices after a failed read;
// manual PCN entry is a form; the chooser steps aside once a way in is chosen. ----
R("if(/^sorted\\.local\\./.test(k)){st.removeItem(k);return}",
  "if(/^sorted\\.(?:local|form)\\./.test(k)){st.removeItem(k);return}");
R("function go(view){",
  "/* v125: words typed into a form on a case (your next step, a pasted message, a correction, how it ended...) are kept when\n   you leave the form or the case, on this phone for this session, and offered back when you return. Removed by\n   clearLocalUserData() like any other copy. */\nvar KEEP_PANELS=[\"move\",\"paste\",\"partly\",\"correct\",\"rename\",\"refadd\",\"promise\",\"done\",\"call\",\"claim\"];\nvar KEEP_SKIP=/^(?:when|via|k|kind|err|caseErr|step|picked|matchId|mreplaces|asked|followUp|mhint|tab)$/;\nfunction keepKey(){return \"sorted.form.\"+(S.user?S.user.id:\"none\")}\nfunction keepAll(){var kk=keepKey();if(!S.formKeep||S.formKeepK!==kk){S.formKeepK=kk;try{S.formKeep=JSON.parse(sessionStorage.getItem(kk)||\"{}\")||{}}catch(e){S.formKeep={}}}return S.formKeep}\nfunction keepWrite(){try{sessionStorage.setItem(keepKey(),JSON.stringify(S.formKeep||{}))}catch(e){}}\nfunction keepWords(d){var w=\"\";Object.keys(d||{}).forEach(function(k){var v=d[k];if(!w&&typeof v===\"string\"&&!KEEP_SKIP.test(k)&&v.trim().length>=3)w=v.trim()});return w}\nfunction formKeepSnap(nextView,nextPanel){\n  var v=S.view;if(!v||v.name!==\"task\"||!v.panel||KEEP_PANELS.indexOf(v.panel)<0)return;\n  if(nextView&&nextView.name===\"task\"&&nextView.id===v.id&&(nextView.panel||null)===v.panel)return;\n  if(!nextView&&nextPanel===v.panel)return;\n  var w=keepWords(S.draft);if(!w)return;\n  keepAll()[v.id]={panel:v.panel,draft:JSON.parse(JSON.stringify(S.draft||{})),words:w.slice(0,90),at:Date.now()};keepWrite();\n}\nfunction formKeepTake(id,panel){var a=keepAll(),k=a[id];if(!k||(panel&&k.panel!==panel))return null;delete a[id];keepWrite();return k.draft}\nfunction keepBanner(t){\n  if(S.view.panel||t.board===\"done\")return \"\";var k=keepAll()[t.id];if(!k)return \"\";\n  return '<div class=\"note stack-s keep125\" role=\"status\"><p style=\"margin:0\"><strong>You were writing something here.</strong> “'+esc(k.words)+(k.words.length>=90?\"…\":\"\")+'”</p><div class=\"row\"><button class=\"btn primary\" data-a=\"keep-go\">Carry on writing</button><button class=\"btn quiet\" data-a=\"keep-drop\">Discard it</button></div></div>';\n}\nfunction go(view){formKeepSnap(view);");
R("case \"panel\":S.view.panel=b.getAttribute(\"data-p\")||null;S.view.copyText=null;S.draft={};render();break;",
  "case \"panel\":{var np125=b.getAttribute(\"data-p\")||null;formKeepSnap(null,np125);S.view.panel=np125;S.view.copyText=null;S.draft={};var fk125=S.view.name===\"task\"&&np125?formKeepTake(S.view.id,np125):null;if(fk125)S.draft=fk125;render();break}\n    case \"keep-go\":if(t){var kg=keepAll()[t.id];if(kg){S.view.panel=kg.panel;S.draft=formKeepTake(t.id)||{};render();var kf=document.querySelector(\"#app main form textarea, #app main form input[type=text]\");if(kf){kf.focus();kf.scrollIntoView({block:\"center\"})}}}break;\n    case \"keep-drop\":if(t){formKeepTake(t.id);render()}break;");
R("if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(mvd)){d.err=\"Pick the day you’re moving, even if it’s a rough date.\";render();return}",
  "if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(mvd)){d.mvAns={tenure:pick(\"mv-tenure\"),council:pick(\"mv-council\"),car:pick(\"mv-car\"),bb:pick(\"mv-bb\"),nation:pick(\"mv-nation\")};d.err=\"Pick the day you’re moving, even if it’s a rough date. Your other answers are kept.\";render();var mdi=$(\"#mv-date\");if(mdi)mdi.focus();return}");
R("var m=S.view.id?momOf(S.view.id):null,a=(m&&m.ans)||{},d=S.draft;",
  "var m=S.view.id?momOf(S.view.id):null,d=S.draft,a=Object.assign({},(m&&m.ans)||{});[\"tenure\",\"council\",\"car\",\"bb\",\"nation\"].forEach(function(k){var v=(d.mvAns&&d.mvAns[k])||d[\"mv-\"+k];if(v)a[k]=v});");
R("open.slice(0,8).forEach(function(t){h+='<button class=\"btn block\" style=\"justify-content:flex-start;text-align:left\" data-a=\"inbound-use\" data-id=\"'+esc(t.id)+'\">'+esc(t.title)+'</button>'});",
  "h+=pickSearch(open.length);open.forEach(function(t){h+='<button class=\"btn block pick125\" style=\"justify-content:flex-start;text-align:left\" data-a=\"inbound-use\" data-id=\"'+esc(t.id)+'\" data-find=\"'+esc(caseText(t))+'\">'+esc(home54Title(t))+'</button>'});h+=pickNone();");
R("return {m:m,list:list.slice(0,6)}}",
  "return {m:m,list:list}}\n/* v125: a list of cases to choose from shows every one; with more than six, a search box filters them as you type */\nfunction pickSearch(n){return n>6?'<label class=\"f\"><span class=\"hint\">Find the case: a name, company or reference</span><input type=\"search\" id=\"pick-q\" autocomplete=\"off\" enterkeyhint=\"search\"></label>':''}\nfunction pickNone(){return '<p class=\"muted pick125-none\" hidden>No case matches. Try another word, or start a new case.</p>'}\nfunction pickFilter(q){q=String(q||\"\").toLowerCase().replace(/\\s+/g,\" \").trim();var ws=q?q.split(\" \"):[],n=0;document.querySelectorAll(\".pick125\").forEach(function(b){var x=(b.getAttribute(\"data-find\")||\"\")+\" \"+(b.textContent||\"\").toLowerCase();var ok=ws.every(function(w){return x.indexOf(w)>=0});b.hidden=!ok;b.style.display=ok?\"\":\"none\";if(ok)n++});var no=document.querySelector(\".pick125-none\");if(no){no.hidden=n>0;no.style.display=n>0?\"none\":\"\"}}");
R("  sc.list.forEach(function(x){h+='<button type=\"button\" class=\"btn block share-to'+(x===sc.m?' primary':'')+'\" data-a=\"share-to\" data-id=\"'+x.id+'\">",
  "  h+=pickSearch(sc.list.length);sc.list.forEach(function(x){h+='<button type=\"button\" class=\"btn block share-to pick125'+(x===sc.m?' primary':'')+'\" data-a=\"share-to\" data-id=\"'+x.id+'\" data-find=\"'+esc(caseText(x))+'\">");
R("  return h+'<button type=\"button\" class=\"btn block\" data-a=\"share-new\">Start a new case</button></div>';",
  "  return h+pickNone()+'<button type=\"button\" class=\"btn block\" data-a=\"share-new\">Start a new case</button></div>';");
R("document.addEventListener(\"input\",function(e){if(e.target&&e.target.id===\"ex-search\"){",
  "document.addEventListener(\"input\",function(e){if(e.target&&e.target.id===\"pick-q\"){pickFilter(e.target.value);return}if(e.target&&e.target.id===\"ex-search\"){");
R("with its history, any helper link and its reminders. This can’t be undone.",
  "with its history, any helper link and its reminders. For two minutes afterwards you can undo it from Home, on this page only. After that it can’t be brought back.");
R("go({name:\"task\",id:t.id,panel:mode===\"call\"&&!frRenewOnly(t)&&!turnAsk(t)?\"call\":null});",
  "go({name:\"task\",id:t.id,panel:mode===\"call\"&&!frRenewOnly(t)&&!turnAsk(t)&&!t.cf&&!pcnRead(String(t.said||\"\"))?\"call\":null});");
R("function viewTask(){",
  "/* v125: the case page leads with what state it is in and the one next step, then the action. The first response, What\n   Sorted understood and its questions follow the action, before the history. */\nfunction nowLine(t,s){\n  if(s===\"done\"||t.example)return \"\";\n  var p=openPromise(t),mv=openMove(t),tx=\"\",lab=\"Next\";\n  if(mv&&!(mv.src===\"parking\"&&pkOn(t)))tx=mv.what.replace(/[.!]+$/,\"\")+(mv.dueAt?\", \"+whenText(mv).replace(/^By/,\"by\"):\"\");\n  else if(p&&(s===\"waiting\"||s===\"waitdue\")){lab=\"Waiting for \"+(p.party||\"them\");tx=whenText(p).replace(/^By/,\"by\")}\n  else tx=String(nextStepText(t)||\"\").replace(/^Next:\\s*/,\"\");\n  if(!tx)return \"\";if(lab===\"Next\"&&/^[A-Z][a-z]/.test(tx)&&!/^(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|January|February|March|April|May|June|July|August|September|October|November|December)\\b/.test(tx))tx=tx.charAt(0).toLowerCase()+tx.slice(1);\n  return '<p class=\"now125\"><strong>'+esc(lab)+':</strong> '+esc(tx)+'</p>';\n}\nfunction viewTask(){S._info=\"\";var html=viewTask124(),info=S._info||\"\";S._info=\"\";var a=html.indexOf(\"\\u0001\");if(a<0)return html.replace(/\\u0002/g,\"\");html=html.replace(\"\\u0001\",\"\");var b=html.indexOf(\"\\u0002\");if(b<0)b=html.lastIndexOf(\"</main>\");if(b<0)b=html.length;return (html.slice(0,b)+info+html.slice(b)).replace(/\\u0002/g,\"\")}\nfunction viewTask124(){");
R("+hoLine(t)+momLine(t)+",
  "+hoLine(t)+momLine(t)+nowLine(t,s)+");
R("+frCard(t)+healthLine(t,s)+uCard(t);",
  "+keepBanner(t)+healthLine(t,s)+\"\\u0001\";S._info=frCard(t)+uCard(t);");
R("+case75Secondary(t,s)",
  "+\"\\u0002\"+case75Secondary(t,s)",5);
R("h+=case75Secondary(t,s);",
  "h+=\"\\u0002\"+case75Secondary(t,s);");
R("Sorted reads it on your phone. Nothing is uploaded.</p>",
  "Sorted reads it on your phone. Nothing is uploaded. For a scanned PDF it reads the first page only.</p>");
R("Or type them in: the PCN number, who issued it and the date.</p>",
  "Or type them in: the PCN number, who issued it and the date.</p><p class=\"muted\" style=\"margin:0;font-size:14px\">Photos and PDFs are read on your phone. For a scanned PDF, only the first page is read.</p>");
R("+'</p>'+docRouteButtons(\"f-case\")+'</section>';\n  return h;\n}",
  "+'</p>'+docRouteButtons(\"f-case\",true)+'</section>';\n  return h;\n}");
R("function docRouteButtons(target){\n  return '<div class=\"row doc121-routes\"><label class=\"btn primary\">Retake photo<input type=\"file\" accept=\"image/*\" capture=\"environment\" data-ocr=\"'+target+'\" class=\"sr-only\"></label><label class=\"btn\">Choose another file<input type=\"file\" accept=\"image/*,application/pdf,.pdf\" data-ocr=\"'+target+'\" class=\"sr-only\"></label><button type=\"button\" class=\"btn\" data-a=\"doc-manual\">Enter the details manually</button></div>';\n}",
  "function docRouteButtons(target,noManual){\n  return '<div class=\"row doc121-routes\"><label class=\"btn primary\">Retake photo<input type=\"file\" accept=\"image/*\" capture=\"environment\" data-ocr=\"'+target+'\" class=\"sr-only\"></label><label class=\"btn\">Choose another file<input type=\"file\" accept=\"image/*,application/pdf,.pdf\" data-ocr=\"'+target+'\" class=\"sr-only\"></label>'+(noManual?'':'<button type=\"button\" class=\"btn\" data-a=\"doc-manual\">Enter the details manually</button>')+'</div>';\n}");
R("function docBlock(){\n  var d=S.draft,r=d&&d.doc;if(!r)return \"\";",
  "function docBlock(){\n  var d=S.draft,r=d&&d.doc;if(!r)return \"\";\n  if(r.status===\"manual\"){\n    var mv=d.docVals||{},mk=mv.kind||\"council\",mh='<section class=\"sheet stack doc121 doc121-review doc125-manual\" aria-labelledby=\"doc121-h\"><div class=\"stack-s\"><p class=\"eyebrow\">Parking notice</p><h2 class=\"h2\" id=\"doc121-h\" tabindex=\"-1\">Enter the notice details</h2><p class=\"muted\" style=\"font-size:16px;margin:0\">Type them from the notice. Leave out anything it doesn’t show. The PCN number or who sent it is enough to start.</p></div><form class=\"stack-s\" data-f=\"doc\"><fieldset class=\"stack-s\" style=\"border:0;padding:0;margin:0\"><legend class=\"h3\" style=\"padding:0\">Who sent it?</legend><div class=\"chips\">'+[[\"council\",\"A council or TfL\"],[\"private\",\"A private parking company\"]].map(function(x){return '<label class=\"chip\"><input type=\"radio\" name=\"doc-kind\" value=\"'+x[0]+'\"'+(mk===x[0]?' checked':'')+'> '+x[1]+'</label>'}).join(\"\")+'</div></fieldset>';\n    DOC_FIELDS.forEach(function(x){var k=x[0];mh+='<label class=\"f\"><span>'+esc(x[1])+'</span><input type=\"text\" id=\"doc-'+k+'\" name=\"doc-'+k+'\" autocomplete=\"off\" maxlength=\"80\" value=\"'+esc(mv[k]||\"\")+'\"></label>'});\n    if(d.docErr)mh+='<p class=\"err\">'+esc(d.docErr)+'</p>';\n    return mh+'<button class=\"btn primary block\" type=\"submit\">Save these details</button></form><label class=\"link\" style=\"align-self:flex-start\">Use a photo instead<input type=\"file\" accept=\"image/*,application/pdf,.pdf\" data-ocr=\"f-case\" class=\"sr-only\"></label></section>';\n  }");
R("var f0=dr2.pcn.f,facts={},L=[];",
  "var f0=dr2.pcn.f,facts={},L=[];\n    if(dr2.status===\"manual\"){var dk125=document.querySelector('input[name=\"doc-kind\"]:checked');dr2.pcn.kind=dk125&&dk125.value===\"private\"?\"private\":\"council\";vals.kind=dr2.pcn.kind;facts.type={v:dr2.pcn.kind===\"private\"?\"Parking charge from a private company\":\"Penalty Charge Notice from a council\",how:\"you\"}}");
R("d.docConfirmed={kind:dr2.pcn.kind,f:facts,src:dr2.expect===\"pcn\"||true?\"the photo you added\":\"the photo you added\"};d.casetext=ctx2;d.skipPk=true;d.pkShort=false;d.src=\"a photo\";",
  "var man125=dr2.status===\"manual\";d.docConfirmed={kind:dr2.pcn.kind,f:facts,src:man125?\"what you typed from the notice\":\"the photo you added\",manual:man125};d.casetext=ctx2;d.skipPk=true;d.pkShort=false;d.src=man125?\"\":\"a photo\";");
R("log(t,\"Read from a photo of the notice and checked by you: \"+Object.keys(dc.f).length+\" details.\");",
  "log(t,(dc.manual?\"Typed in from the notice by you: \":\"Read from a photo of the notice and checked by you: \")+Object.keys(dc.f).length+\" details.\");");
R("case \"doc-manual\":{d.doc=null;d.docVals={};d.docErr=\"\";d.docManual=true;d.pkShort=false;d.skipPk=true;render();",
  "case \"doc-manual\":{var dmx=docExpect()===\"pcn\"||!!(d.doc&&d.doc.expect===\"pcn\");if(dmx){d.doc={status:\"manual\",expect:\"pcn\",pcn:{kind:\"council\",f:{}},quality:{}};d.docVals={};d.docErr=\"\";docTrack(\"document_manual_fallback\",{expect:\"pcn\"});render();ocrStatus(\"Enter the details from the notice.\");var mh1=document.getElementById(\"doc121-h\");if(mh1){mh1.focus();mh1.scrollIntoView({block:\"start\"})}break}\n      d.doc=null;d.docVals={};d.docErr=\"\";d.docManual=true;d.pkShort=false;d.skipPk=true;render();");
R("  var docb=docBlock();\n  return '<section class=\"stack\">'+((gk||giStored())&&!d.matchId&&!d.vague&&!d.pkShort&&!d.fromShare?'<button type=\"button\" class=\"link\" data-a=\"gi-back\" style=\"align-self:flex-start;min-height:0;padding:0\">← Choose something else</button>':'')+docb+(S.tasks.length?'<h2 class=\"h2\">What do you need to sort out?</h2>':'<h1 class=\"h1\">What do you need to sort out?</h1>')+'<form class=\"stack-s\" data-f=\"case\">'+",
  "  var docb=docBlock(),isDoc=gk===\"document\",hd=isDoc?\"Start with your document\":\"What do you need to sort out?\";\n  return '<section class=\"stack start125'+(gk?' start-active':'')+'\">'+((gk||giStored()||docb)&&!d.matchId&&!d.vague&&!d.fromShare?'<button type=\"button\" class=\"link\" data-a=\"gi-back\" style=\"align-self:flex-start;min-height:0;padding:0\">← Choose something else</button>':'')+docb+(docb?'':(S.tasks.length?'<h2 class=\"h2\">'+hd+'</h2>':'<h1 class=\"h1\">'+hd+'</h1>'))+'<form class=\"stack-s\" data-f=\"case\"'+(docb?' hidden style=\"display:none\"':'')+'>'+");
R("<label class=\"f\"><span class=\"hint\">Tell Sorted in one sentence, or paste the message they sent you. Leave out bank details and health information.</span><textarea id=\"f-case\" name=\"casetext\" rows=\"3\" placeholder=\"Washing machine stopped draining\">'+esc(d.casetext||\"\")+'</textarea></label>'+(d.caseErr?'<p class=\"err\">'+esc(d.caseErr)+'</p>':'')+(giKind()===\"document\"?'<label class=\"btn primary block gi-photo\">Take a photo or choose the letter<input type=\"file\" accept=\"image/*,application/pdf,.pdf\" data-ocr=\"f-case\" class=\"sr-only\"></label><p class=\"muted\" style=\"font-size:15px;margin:0\">Sorted reads it on your phone. Nothing is uploaded. Sorted tries to read the notice. Check the details before continuing. Or paste the words above.</p><p class=\"muted\" id=\"ocr-status\" role=\"status\" aria-live=\"polite\" style=\"font-size:15px;margin:0\"></p>':picPicker(\"f-case\"))+",
  "'+(isDoc?'<label class=\"btn primary block gi-photo\">Take a photo or choose the letter<input type=\"file\" accept=\"image/*,application/pdf,.pdf\" data-ocr=\"f-case\" class=\"sr-only\"></label><p class=\"muted\" style=\"font-size:15px;margin:0\">Sorted reads it on your phone. Nothing is uploaded. Sorted tries to read the notice. Check the details before continuing. For a scanned PDF, only the first page is read.</p><p class=\"muted\" id=\"ocr-status\" role=\"status\" aria-live=\"polite\" style=\"font-size:15px;margin:0\"></p>':'')+'<label class=\"f\"><span class=\"'+(isDoc?'h3':'hint')+'\">'+(isDoc?'Or type what it says':'Tell Sorted in one sentence, or paste the message they sent you. Leave out bank details and health information.')+'</span><textarea id=\"f-case\" name=\"casetext\" rows=\"3\" placeholder=\"'+(isDoc?'Who sent it, what it asks and any date on it':'Washing machine stopped draining')+'\">'+esc(d.casetext||\"\")+'</textarea></label>'+(d.caseErr?'<p class=\"err\">'+esc(d.caseErr)+'</p>':'')+(isDoc?'':picPicker(\"f-case\"))+");
R("    if(home){var p=home.querySelector('#cap82-start');if(!p){",
  "    if(home){var p=home.querySelector('#cap82-start');if(home.querySelector('.gi-form,.start-active,.doc121')){if(p)p.remove();return}if(!p){");
R(".u117 dd{margin:0;overflow-wrap:anywhere}",
  ".u117 dd{margin:0;overflow-wrap:anywhere}\n.now125{margin:2px 0 0;font-size:17px;line-height:1.4}\n.now125 strong{font-weight:700}\n.keep125 .row{gap:8px;flex-wrap:wrap}\n.doc125-manual .chips label.chip{min-height:44px}");
R("['What did you receive?','Tell Sorted what the letter or document is about, or add it below.']",
  "['Start with your document','Add a photo or PDF of the letter, notice or bill, or type what it says.']",2);
R("document:['What did you receive?','Tell Sorted what the letter or document is about, or add it below.','What did you receive, and what does it seem to be about?…']",
  "document:['Start with your document','Add a photo or PDF of the letter, notice or bill, or type what it says.','Who sent it, what it asks and any date on it…']");
R("/^What did you receive\\?$/.test(t)",
  "/^What did you receive\\?$/.test(t)||/^Start with your document$/.test(t)");
R("if(d.docBusy)return;d.docBusy=true;",
  "if(d.docBusy)return;d.docBusy=true;d.docErr=\"\";");
R("EVQ=[];S.draft={};S.pendingMom=null;",
  "EVQ=[];S.draft={};S.formKeep=null;S.pendingMom=null;");
fs.writeFileSync('public/index.html',s);
const EXPECT='e9350d1a71bade80f173e98d704aa568532f4f6d';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v125 ok',h(s),s.length);
