const fs=require('fs'),c=require('crypto');const h=b=>c.createHash('sha1').update(b).digest('hex');
let s=fs.readFileSync('public/index.html','utf8');
if(h(s)!=='e62a9652860a8e1b8f2d349495eca8f693140f67')throw new Error('base mismatch '+h(s));
function R(a,b,n){n=n||1;const k=s.split(a).length-1;if(k!==n)throw new Error('match '+k+': '+a.slice(0,60));s=s.split(a).join(b)}
// ---- v69: company scores. Kept and missed promises with companies on the fixed list go to anonymous totals through
// record_outcome(); company_scores() returns totals with at least 5 promises from 3 people. Never case text. ----
R("function readCase(t,f){",
  "/* v69: company scores. Kept and missed promises with companies on Sorted's fixed list are added to anonymous totals\n   (company, kept or missed, how you contacted them; never case text). Shown only with 5 promises from 3 people. */\nvar SC_PARTIES=PARTIES.map(function(x){return x[1]}).filter(function(n){return !/^the /.test(n)});\nfunction scParty(t,p){var n=String((p&&p.party)||(t.facts&&t.facts.party)||\"\").trim();for(var i=0;i<SC_PARTIES.length;i++)if(SC_PARTIES[i].toLowerCase()===n.toLowerCase())return SC_PARTIES[i];return \"\"}\nfunction recordOutcome(t,p,outcome){\n  if(!S.user||!t||!p||t.example||p.src===\"parking\"||noSteps())return;var party=scParty(t,p);if(!party)return;\n  var via=t.call&&t.call.via?String(t.call.via):\"\";\n  try{sb.rpc(\"record_outcome\",{p_promise:String(p.id||\"\").slice(0,40),p_party:party,p_outcome:outcome,p_via:/^(phone|email|account|letter|app)$/.test(via)?via:\"\"}).then(function(){},function(){})}catch(e){}\n}\nfunction loadScores(){\n  if(!S.user||(S.scoresAt&&Date.now()-S.scoresAt<6*HOUR))return;S.scoresAt=Date.now();\n  try{sb.rpc(\"company_scores\").then(function(r){if(r&&!r.error&&Array.isArray(r.data)){S.scores={};r.data.forEach(function(x){S.scores[x.party]=x});if(S.view.name===\"task\")render()}},function(){})}catch(e){}\n}\nfunction scoreBlock(t){\n  if(t.example||pkOn(t))return \"\";var op=openPromise(t)||(t.promises||[])[t.promises.length-1],party=scParty(t,op);if(!party||!S.scores||!S.scores[party])return \"\";\n  var s=S.scores[party],n=s.kept+s.missed,pct=Math.round(s.kept*100/n),best=null;\n  Object.keys(s.by_via||{}).forEach(function(v){var x=s.by_via[v];if(x.n>=5&&(!best||x.kept/x.n>best.r))best={v:v,r:x.kept/x.n}});\n  var vl={phone:\"by phone\",email:\"by email\",account:\"through their app or account\",app:\"through their app\",letter:\"by letter\"};\n  return '<section class=\"stack-s mem-block sc-block\" aria-labelledby=\"sch\"><h2 class=\"h3\" id=\"sch\">Across Sorted: '+esc(party)+'</h2><p style=\"margin:0\">People recorded '+n+' promises from '+esc(party)+'. '+s.kept+' were kept ('+pct+'%).'+(best&&vl[best.v]?' Promises made '+vl[best.v]+' were kept '+Math.round(best.r*100)+'% of the time.':'')+'</p><p class=\"muted\" style=\"font-size:14px;margin:0\">From '+s.people+' people over the last 12 months. It isn’t a review, just what people recorded in Sorted.</p></section>';\n}\nfunction readCase(t,f){");
R("case \"kept\":if(t){var p=openPromise(t);p.status=\"kept\";p.closedAt=nowIso();track(\"outcome_kept\",t,{promise_id:p.id});",
  "case \"kept\":if(t){var p=openPromise(t);p.status=\"kept\";p.closedAt=nowIso();track(\"outcome_kept\",t,{promise_id:p.id});recordOutcome(t,p,\"kept\");");
R("case \"missed\":if(t){var q=openPromise(t);q.status=\"missed\";q.closedAt=nowIso();track(\"outcome_missed\",t,{promise_id:q.id});",
  "case \"missed\":if(t){var q=openPromise(t);q.status=\"missed\";q.closedAt=nowIso();track(\"outcome_missed\",t,{promise_id:q.id});recordOutcome(t,q,\"missed\");");
R("  h+=xrBlock(t);\n",
  "  loadScores();\n  h+=xrBlock(t);\n  h+=scoreBlock(t);\n");
R("'<p><strong>Why Sorted can use your data.</strong> Sorted holds your cases to give you the service you asked for. It keeps step records because it has a legitimate interest in learning whether the pilot works, and you can turn them off. Sorted is for people aged 18 and over.</p>'",
  "'<p><strong>Company scores.</strong> When you record that a company kept or missed a promise, Sorted adds it to totals for that company: the company’s name (only large companies on a fixed list), kept or missed, and how you contacted them. Never what your case is about. Totals only show once at least 5 promises from 3 people are recorded, and nobody, including the person running the pilot, sees who recorded what. They are deleted after 12 months, or straight away if you delete your account. Turning off step records on a phone also stops this.</p>'+\n  '<p><strong>Why Sorted can use your data.</strong> Sorted holds your cases to give you the service you asked for. It keeps step records because it has a legitimate interest in learning whether the pilot works, and you can turn them off. Company totals rely on a legitimate interest in showing people how often companies keep their promises. Sorted is for people aged 18 and over.</p>'");
fs.writeFileSync('public/index.html',s);
const EXPECT='d14a3adec8287c540d9cc201797f50fdeae9731e';
if(EXPECT&&h(s)!==EXPECT)throw new Error('output mismatch '+h(s));
console.log('v69 ok',h(s),s.length);
