# v63: challenge builder, release 4. Tick what's true; Sorted writes from that and the confirmed facts only; then checks it.
import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dates
from playwright.sync_api import sync_playwright
HERE = os.path.abspath('.'); errs = []; fails = []
def ok(c, m):
    print(('PASS ' if c else 'FAIL ') + m)
    if not c: fails.append(m)
def wait(pg, ms=350): pg.wait_for_timeout(ms)
T0 = datetime.date.today()
def uk(n): return (T0 + datetime.timedelta(days=n)).strftime('%d/%m/%Y')
def lab(n): x = T0 + datetime.timedelta(days=n); return '%d %s %d' % (x.day, x.strftime('%b'), x.year)
def tasks(pg): return pg.evaluate("JSON.parse(localStorage.getItem('__mockdb')).tasks.map(y=>y.data)")
def case(pg, title): return next((x for x in tasks(pg) if x['title'] == title), None)
def start(pg, text):
    pg.goto('https://sorted.test/'); wait(pg, 400)
    if pg.locator('[data-a=compose]').count(): pg.click('[data-a=compose]'); wait(pg)
    pg.fill('#f-case', text); pg.click('form[data-f=case] button[type=submit]'); wait(pg)
    if pg.locator('[data-a=match-new]').count(): pg.click('[data-a=match-new]'); wait(pg)
    if pg.locator('[data-a=vague-go]').count(): pg.click('[data-a=vague-go]'); wait(pg)
    pg.click('form[data-f=baseline] .chip >> nth=0'); pg.click('form[data-f=baseline] button[type=submit]'); wait(pg, 450)
    if pg.locator('[data-a=cf-yes]').count(): pg.click('[data-a=cf-yes]'); wait(pg)
def checks(pg): return [x.strip() for x in pg.locator('.bd-check li').all_text_contents()]
with sync_playwright() as p:
    b = p.chromium.launch(); ctx = b.new_context(viewport={'width': 390, 'height': 844}, timezone_id='Europe/London')
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'], origin='https://sorted.test')
    ctx.route('https://cdn.jsdelivr.net/**', lambda r: r.fulfill(path=HERE + '/tests/mock.js', content_type='application/javascript'))
    ctx.route(lambda u: u.startswith('https://sorted.test/'), lambda r: r.fulfill(path=HERE + '/tests/out/index.html', content_type='text/html') if '/art/' not in r.request.url else r.fulfill(body=''))
    pg = ctx.new_page(); pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('https://sorted.test/#start'); pg.evaluate("localStorage.clear();localStorage.setItem('__emailReady','1')"); pg.reload(); wait(pg, 200); pg.click('[data-a=anon-start]'); wait(pg)
    T = 'Southwark PCN · SK12345678'
    start(pg, "London Borough of Southwark PENALTY CHARGE NOTICE PCN Number: SK12345678 Vehicle Registration Mark: AB12 CDE Date of contravention: %s Location: Lordship Lane SE22 Contravention code: 12 Parked in a residents' or shared use parking place without a permit. The penalty charge is £130. If paid within 14 days, reduced to £65." % uk(-2))
    ok(pg.locator('.pk-card [data-a=panel][data-p=pkbuild]').inner_text() == 'Help me write a challenge', 'the parking card offers to help write the challenge')
    pg.click('.pk-card [data-a=panel][data-p=pkbuild]'); wait(pg)
    ok('Sorted only writes what you tick' in pg.inner_text('main'), 'it says it only writes what you tick')
    ok(pg.locator('input[name=bdg-sold]').count() == 0, 'no "didn’t own it" option at the ticket stage')
    pg.click('form[data-f=pkbuild] button[type=submit]'); wait(pg)
    ok('Tick at least one thing' in pg.inner_text('main'), 'nothing ticked: it asks for at least one reason')
    ok(pg.locator('textarea[name=bdd-paid]').is_visible() is False, 'the "own words" box only opens when you tick')
    pg.check('input[name=bdg-paid]'); wait(pg, 100)
    ok(pg.locator('textarea[name=bdd-paid]').is_visible(), 'ticking opens the "own words" box')
    pg.fill('textarea[name=bdd-paid]', 'I paid at 10:05 on RingGo, session 445821')
    pg.check('input[name=bde-receipt]')
    pg.click('form[data-f=pkbuild] button[type=submit]'); wait(pg)
    draft = pg.input_value('#f-bdtext')
    ok(draft.startswith('Dear Southwark Council,') and ('Penalty Charge Notice SK12345678, vehicle AB12 CDE, %s, Lordship Lane SE22.' % lab(-2)) in draft, 'it opens with who and the confirmed details')
    ok('I am challenging this penalty charge and ask you to cancel it.' in draft, 'it says what you want')
    ok('I paid for parking for this time. I paid at 10:05 on RingGo, session 445821.' in draft, 'it uses your reason in your words')
    ok('I have attached a payment receipt or app screenshot.' in draft and 'please offer the reduced amount again' in draft, 'it lists your evidence and asks for the reduced amount again')
    ok('sign' not in draft.lower() and 'blue badge' not in draft.lower() and 'broken' not in draft.lower(), 'nothing you didn’t tick')
    used = pg.inner_text('.bd-used summary')
    ok(used.startswith('Uses 6 confirmed details and 2 things you told Sorted'), 'it says what it used: %s' % used)
    c = checks(pg)
    ok(c[0].startswith('✓') and 'SK12345678' in c[0] and c[1].startswith('✓') and c[2].startswith('✓') and c[3].startswith('!') and 'name and address' in c[3], 'ready to send? ref, what happened, what you want; name and address still to add')
    ok('can’t tell you whether they’ll agree' in pg.inner_text('.bd-check') and '%' not in pg.inner_text('.bd-check'), 'no chance of winning')
    pg.screenshot(path=HERE + '/tests/out/builder_draft.png', full_page=True)
    # a reason with no evidence gets flagged
    pg.click('[data-a=panel][data-p=pkbuild]'); wait(pg)
    ok(pg.is_checked('input[name=bdg-paid]') and pg.input_value('textarea[name=bdd-paid]').startswith('I paid at 10:05'), 'your answers are kept when you go back')
    pg.uncheck('input[name=bde-receipt]'); pg.check('input[name=bdg-signs]'); pg.click('form[data-f=pkbuild] button[type=submit]'); wait(pg)
    ok(any('“the signs or road markings were unclear or missing”' in x and 'Photos of the signs' in x for x in checks(pg)), 'a reason with no evidence ticked is flagged')
    # your edits, checked again
    pg.fill('#f-bdtext', pg.input_value('#f-bdtext').replace('[Your name]', 'Baldwin Example').replace('[Your address]', '1 Test Road, London'))
    pg.click('[data-a=bd-recheck]'); wait(pg)
    ok(any(x.startswith('✓') and 'name and address are in' in x for x in checks(pg)), 'after you add your name, the check passes')
    pg.click('[data-a=bd-copy]'); wait(pg)
    clip = pg.evaluate('navigator.clipboard.readText()')
    ok('Baldwin Example' in clip and 'SK12345678' in clip, 'copy puts your edited version on the clipboard')
    ok(any(e['label'] == 'Copied the challenge Sorted wrote.' for e in case(pg, T)['events']), 'the history notes it was copied')
    # sending it keeps the exact text
    pg.click('form[data-f=pkdraft] button[type=submit]'); wait(pg)
    ok(pg.locator('form[data-f=pksent]').count() == 1 and 'Baldwin Example' in pg.input_value('#f-pktext'), '"I’ve sent it" goes to the proof form with your text')
    pg.fill('#f-pkref', 'CH-77'); pg.click('form[data-f=pksent] button[type=submit]'); wait(pg)
    t = case(pg, T)
    ok(t['pk']['subs'][0]['text'].startswith('Dear Southwark Council,') and 'Baldwin Example' in t['pk']['subs'][0]['text'], 'the exact words you sent are kept in the case')
    # formal stage
    start(pg, "London Borough of Camden NOTICE TO OWNER PCN Number: CU98765432 Vehicle: LK70 XYZ Date of notice: %s Date of contravention: %s The penalty charge of £160 has not been paid." % (uk(-1), uk(-20)))
    ok(pg.locator('.pk-card [data-a=panel][data-p=pkbuild]').inner_text() == 'Help me write a formal challenge', 'Notice to Owner: help with a formal challenge')
    pg.click('.pk-card [data-a=panel][data-p=pkbuild]'); wait(pg)
    ok(pg.locator('input[name=bdg-sold]').count() == 1, '"I didn’t own the vehicle then" is offered at this stage')
    pg.check('input[name=bdg-sold]'); pg.fill('textarea[name=bdd-sold]', 'I sold it on 1 August'); pg.click('form[data-f=pkbuild] button[type=submit]'); wait(pg)
    draft = pg.input_value('#f-bdtext')
    ok('I am making formal representations against this Notice to Owner and ask you to cancel it.' in draft and 'I did not own the vehicle at the time. I sold it on 1 August.' in draft, 'formal wording, your reason')
    ok('reduced amount' not in draft, 'no reduced-price line when there isn’t one')
    # private
    start(pg, "ParkingEye Ltd PARKING CHARGE NOTICE Reference number: 1234567 Vehicle registration: YT19 ABC Date of event: %s Parking charge amount: £100. Reduced to £60 if paid within 14 days. Appeals: POPLA." % uk(-1))
    pg.click('.pk-card [data-a=panel][data-p=pkbuild]'); wait(pg); pg.check('input[name=bdg-badge]'); pg.click('form[data-f=pkbuild] button[type=submit]'); wait(pg)
    draft = pg.input_value('#f-bdtext')
    ok(draft.startswith('Dear ParkingEye,') and 'Parking charge 1234567' in draft and 'I am challenging this parking charge' in draft and 'reduced amount' not in draft, 'private: their name, "parking charge", no council wording')
    b.close()
print('ERRORS', errs); print('FAILS', fails)
