// Writes supabase/functions/inbound-email/readers.mjs from the built page, so the server reads a reply with the same
// patterns as the phone. Run after `node all.js`: node tools/make_server_reader.js  (tests/34_reply_kinds.py checks it is fresh).
const fs=require('fs');
const s=fs.readFileSync('public/index.html','utf8');
function line(name){const a='var '+name+'=';const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(name+' not found exactly once');return 'export const '+name+'='+s.slice(i+a.length,s.indexOf(';\n',i))+';'}
const out=`// Generated by tools/make_server_reader.js from the page (public/index.html). Do not edit by hand.
// The reply patterns are the page's own (RS_NO, RS_YES, RS_ACK), so the server and the phone agree.
${line('RS_NO')}
${line('RS_YES')}
${line('RS_ACK')}
// A reply that mentions a day or a number of days, with a promise word: it may give a new date. Only a hint for the
// notification; the phone's own reader proposes the actual date when the person opens the case.
export const RD_DATE=/\\b(?:will|should|expect|expected|aim|arrange[ds]?|book(?:ed)?|scheduled|processed|arrive|be with you)\\b[^.!?]{0,80}\\b(?:today|tomorrow|(?:mon|tues|wednes|thurs|fri|satur|sun)day|within \\d{1,2} (?:working |business )?days|\\d{1,2}(?:st|nd|rd|th)? (?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\\d{1,2}[\\/.]\\d{1,2}(?:[\\/.]\\d{2,4})?|next week)\\b/i;
// Same order as rsRead() in the page: cancelled, then rejected, then acknowledgement; then a possible date.
export function replyKind(text){
  const x=String(text||"").replace(/\\s+/g," ").trim();
  if(RS_YES.test(x)&&!/\\bnot (?:be )?cancel/i.test(x))return "cancelled";
  if(RS_NO.test(x))return "rejected";
  if(RD_DATE.test(x))return "date";
  if(RS_ACK.test(x))return "ack";
  return "other";
}
`;
fs.writeFileSync(process.argv[2]||'supabase/functions/inbound-email/readers.mjs',out);
