// Generated by tools/make_server_reader.js from the page (public/index.html). Do not edit by hand.
// The reply patterns are the page's own (RS_NO, RS_YES, RS_ACK), so the server and the phone agree.
export const RS_NO=/\b(?:not (?:been )?accept(?:ed)?|unable to accept|cannot accept|can ?not accept|do not accept|does not accept|have been rejected|has been rejected|have rejected|has rejected|we reject|is rejected|are rejected|notice of rejection|decided not to cancel|will not (?:be )?cancel|not be cancelled|remains? (?:payable|valid|outstanding|due)|(?:appeal|representations?) (?:has been |have been |was |were )?(?:refused|dismissed|unsuccessful|rejected))\b/i;
export const RS_YES=/\b(?:(?:has|have) been cancelled|(?:we|i) (?:have|will) cancel(?:led)?|is cancelled|now cancelled|cancelled (?:the|this|your) (?:pcn|penalty|charge|notice)|accepted your (?:challenge|representations?|appeal)|your (?:challenge|representations?|appeal) (?:has been |have been |was |were )?(?:accepted|allowed|upheld|successful)|no further action|(?:pcn|penalty charge|charge) (?:has been |is )?withdrawn)\b/i;
export const RS_ACK=/\b(?:received your (?:challenge|appeal|representations?|correspondence|email|letter)|acknowledge (?:receipt|your)|we will (?:reply|respond|review|consider))\b/i;
// A reply that mentions a day or a number of days, with a promise word: it may give a new date. Only a hint for the
// notification; the phone's own reader proposes the actual date when the person opens the case.
export const RD_DATE=/\b(?:will|should|expect|expected|aim|arrange[ds]?|book(?:ed)?|scheduled|processed|arrive|be with you)\b[^.!?]{0,80}\b(?:today|tomorrow|(?:mon|tues|wednes|thurs|fri|satur|sun)day|within \d{1,2} (?:working |business )?days|\d{1,2}(?:st|nd|rd|th)? (?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\d{1,2}[\/.]\d{1,2}(?:[\/.]\d{2,4})?|next week)\b/i;
// As rsRead() in the page: cancelled before rejected. A possible date comes before a plain acknowledgement, so "we will reply within 14 days" counts as a date.
export function replyKind(text){
  const x=String(text||"").replace(/\s+/g," ").trim();
  if(RS_YES.test(x)&&!/\bnot (?:be )?cancel/i.test(x))return "cancelled";
  if(RS_NO.test(x))return "rejected";
  if(RD_DATE.test(x))return "date";
  if(RS_ACK.test(x))return "ack";
  return "other";
}
